import { PERMISSIONS, SYSTEM_ROLES } from "@/config/permissions.constants";

/**
 * Canonical report-category access mapping.
 * Keep this file as the single source of truth for frontend report permissions.
 */
export const REPORT_CATEGORY_PERMISSIONS = {
  finance: PERMISSIONS.REPORT_FINANCE_VIEW,
  projects: PERMISSIONS.REPORT_PROJECTS_VIEW,
  employees: PERMISSIONS.REPORT_EMPLOYEES_VIEW,
  payroll: PERMISSIONS.REPORT_PAYROLL_VIEW,
  sites: PERMISSIONS.REPORT_SITES_VIEW,
  assets: PERMISSIONS.REPORT_ASSETS_VIEW,
  maintenance: PERMISSIONS.REPORT_MAINTENANCE_VIEW,
  users: PERMISSIONS.REPORT_USERS_VIEW,
  executive: PERMISSIONS.REPORT_SYSTEM_VIEW,
} as const;

export type ReportCategory = keyof typeof REPORT_CATEGORY_PERMISSIONS;

/**
 * Canonical role access per report category.
 * This must mirror reports.routes.tsx policy.
 */
export const REPORT_CATEGORY_ROLES = {
  finance: [SYSTEM_ROLES.SUPERADMIN, SYSTEM_ROLES.ADMIN, SYSTEM_ROLES.FIN_MANAGER],
  projects: [SYSTEM_ROLES.SUPERADMIN, SYSTEM_ROLES.ADMIN, SYSTEM_ROLES.OPS_MANAGER],
  employees: [SYSTEM_ROLES.SUPERADMIN, SYSTEM_ROLES.ADMIN, SYSTEM_ROLES.HR_MANAGER],
  payroll: [
    SYSTEM_ROLES.SUPERADMIN,
    SYSTEM_ROLES.ADMIN,
    SYSTEM_ROLES.HR_MANAGER,
    SYSTEM_ROLES.FIN_MANAGER,
  ],
  sites: [SYSTEM_ROLES.SUPERADMIN, SYSTEM_ROLES.ADMIN, SYSTEM_ROLES.OPS_MANAGER],
  assets: [SYSTEM_ROLES.SUPERADMIN, SYSTEM_ROLES.ADMIN, SYSTEM_ROLES.OPS_MANAGER],
  maintenance: [SYSTEM_ROLES.SUPERADMIN, SYSTEM_ROLES.ADMIN, SYSTEM_ROLES.OPS_MANAGER],
  users: [SYSTEM_ROLES.SUPERADMIN, SYSTEM_ROLES.ADMIN],
  executive: [SYSTEM_ROLES.SUPERADMIN, SYSTEM_ROLES.ADMIN],
} as const;
