/**
 * Employee Types & Interfaces
 * Type definitions for the Employees module based on backend DTOs and Entity
 */

// ============= Enums =============

export enum EmploymentType {
  PERMANENT = "PERMANENT", // موظف دائم
  CONTRACT = "CONTRACT", // عقد محدد المدة
  TEMPORARY = "TEMPORARY", // مؤقت
  PART_TIME = "PART_TIME", // دوام جزئي
  FULL_TIME = "FULL_TIME", // دوام كامل
  FREELANCE = "FREELANCE", // مستقل/حر
  CONSULTANT = "CONSULTANT", // استشاري
  INTERN = "INTERN", // متدرب
  TRAINEE = "TRAINEE", // متدرب تحت التجربة
  SEASONAL = "SEASONAL", // موسمي
  ON_CALL = "ON_CALL", // عند الطلب
  PROBATION = "PROBATION", // تحت الاختبار
  REMOTE = "REMOTE", // عن بُعد
}

export enum EmployeeStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  ON_LEAVE = "ON_LEAVE",
  SUSPENDED = "SUSPENDED",
  TERMINATED = "TERMINATED",
}

export enum Gender {
  MALE = "MALE",
  FEMALE = "FEMALE",
  OTHER = "OTHER",
}

// ============= Entity Interface =============

export interface EmployeeEntity {
  id: string;
  firstName: string;
  lastName: string;
  middleName: string | null;
  fullName: string; // Computed field
  nationalId: string;
  employeeNumber: string;
  email: string | null;
  phone: string;
  alternatePhone: string | null;
  dateOfBirth: string | null; // ISO date string
  gender: Gender | null;
  nationality: string | null;
  address: string | null;
  city: string | null;
  state: string | null;
  postalCode: string | null;
  country: string;
  employmentType: EmploymentType | null;
  status: EmployeeStatus | null;
  departmentId: string | null;
  departmentName: string | null;
  positionId: string | null;
  positionName: string | null;
  hireDate: string; // ISO date string
  terminationDate: string | null;
  terminationReason: string | null;
  rehireDate: string | null;
  rehireReason: string | null;
  emergencyContactName: string | null;
  emergencyContactPhone: string | null;
  emergencyContactRelation: string | null;
  profilePicture: string | null; // Full URL to profile picture
  notes: string | null;
  createdAt: string;
  updatedAt: string;
  // Salary fields (integrated from salary_structures table)
  baseSalary?: number | null;
  currency?: string; // ISO 4217 code (e.g., SAR)
  lastSalaryUpdate?: string | null; // ISO date string
  lastSalaryUpdateBy?: string | null; // User ID who made the update
  version?: number; // Optimistic lock version for concurrent update safety
  rowVersion?: number; // Alias to unify with rowVersion used in other modules
}

// ============= Create DTO =============

export interface CreateEmployeeDto {
  // ✅ REQUIRED FIELDS (7 fields for simplified UX)
  firstName: string;
  lastName: string;
  nationalId: string;
  gender: Gender;
  employmentType: EmploymentType;
  hireDate: string; // ISO date string
  phone: string;

  // ⚪ OPTIONAL FIELDS - ACTIVE IN NEW UI
  email?: string;
  departmentId?: string; // FK to Department
  positionId?: string; // FK to Position
  address?: string;
  nationality?: string;
  baseSalary?: number | null; // 💰 NEW: Can be set during creation or later
  currency?: string; // Default: 'SAR'
  emergencyContactName?: string;
  emergencyContactPhone?: string;

  // Auto-generated fields
  employeeNumber?: string; // Read-only, generated by backend
  status?: EmployeeStatus; // Default: ACTIVE
  country?: string; // Default: 'المملكة العربية السعودية'

  // ⚠️ DEPRECATED FIELDS - Not in new simplified UI (kept for backend compatibility)
  middleName?: string;
  alternatePhone?: string;
  dateOfBirth?: string;
  city?: string;
  state?: string;
  postalCode?: string;
  terminationDate?: string;
  terminationReason?: string;
  emergencyContactRelation?: string;
  notes?: string;
}

// ============= Update DTO =============

export interface UpdateEmployeeDto {
  firstName?: string;
  lastName?: string;
  middleName?: string;
  nationalId?: string;
  email?: string;
  phone?: string;
  alternatePhone?: string;
  dateOfBirth?: string;
  gender?: Gender;
  nationality?: string;
  address?: string;
  city?: string;
  state?: string;
  postalCode?: string;
  country?: string;
  employmentType?: EmploymentType;
  status?: EmployeeStatus;
  departmentId?: string; // FK to Department
  positionId?: string; // FK to Position
  hireDate?: string;
  terminationDate?: string;
  terminationReason?: string;
  emergencyContactName?: string;
  emergencyContactPhone?: string;
  emergencyContactRelation?: string;
  notes?: string;
  version?: number;
  rowVersion?: number;
}

// ============= Rehire DTO =============

export interface RehireEmployeeDto {
  rehireDate: string; // ISO date string
  rehireReason?: string;
  baseSalary?: number;
  departmentId?: string;
  positionId?: string;
}

// ============= Filters DTO =============

export interface EmployeeFiltersDto {
  page?: number;
  pageSize?: number;
  search?: string; // Search in name, email, phone, nationalId
  employmentType?: EmploymentType;
  status?: EmployeeStatus;
  departmentId?: string; // Filter by department ID
  positionId?: string; // Filter by position ID
  nationality?: string;
  country?: string;
  sortBy?: string;
  sortOrder?: "asc" | "desc";
}

// ============= Bulk Create DTO =============

export interface BulkCreateEmployeesDto {
  employees: CreateEmployeeDto[];
}

// ============= Paginated Response =============

export interface PaginatedEmployeesResponse {
  data: EmployeeEntity[];
  total?: number; // Legacy compatibility for older list pages
  meta: {
    page: number;
    pageSize: number;
    totalPages: number;
    totalItems: number;
    hasNextPage: boolean;
    hasPreviousPage: boolean;
  };
}

// ============= Helper Functions =============

/**
 * Get employee status badge color
 */
export const getEmployeeStatusColor = (status: EmployeeStatus): string => {
  const colors: Record<EmployeeStatus, string> = {
    [EmployeeStatus.ACTIVE]: "success",
    [EmployeeStatus.INACTIVE]: "secondary",
    [EmployeeStatus.ON_LEAVE]: "warning",
    [EmployeeStatus.SUSPENDED]: "destructive",
    [EmployeeStatus.TERMINATED]: "destructive",
  };
  return colors[status];
};

/**
 * Get employment type badge color
 */
export const getEmploymentTypeColor = (type: EmploymentType): string => {
  const colors: Record<EmploymentType, string> = {
    [EmploymentType.PERMANENT]: "default",
    [EmploymentType.CONTRACT]: "secondary",
    [EmploymentType.TEMPORARY]: "secondary",
    [EmploymentType.FREELANCE]: "outline",
    [EmploymentType.PART_TIME]: "outline",
    [EmploymentType.FULL_TIME]: "default",
    [EmploymentType.CONSULTANT]: "outline",
    [EmploymentType.INTERN]: "outline",
    [EmploymentType.TRAINEE]: "outline",
    [EmploymentType.SEASONAL]: "secondary",
    [EmploymentType.ON_CALL]: "secondary",
    [EmploymentType.PROBATION]: "secondary",
    [EmploymentType.REMOTE]: "outline",
  };
  return colors[type];
};

/**
 * Get employee full name
 */
export const getEmployeeFullName = (
  employee: EmployeeEntity | CreateEmployeeDto | UpdateEmployeeDto,
): string => {
  const parts = [
    "firstName" in employee ? employee.firstName : "",
    "middleName" in employee ? employee.middleName : "",
    "lastName" in employee ? employee.lastName : "",
  ].filter(Boolean);
  return parts.join(" ");
};

/**
 * Format employee number for display
 */
export const formatEmployeeNumber = (number: string): string => {
  if (!number) return "";
  return number.startsWith("EMP-") ? number : `EMP-${number}`;
};

/**
 * Calculate employment duration in days
 */
export const getEmploymentDuration = (
  hireDate: string,
  terminationDate?: string | null,
): number => {
  const endDate = terminationDate ? new Date(terminationDate) : new Date();
  const startDate = new Date(hireDate);
  const diff = endDate.getTime() - startDate.getTime();
  return Math.floor(diff / (1000 * 60 * 60 * 24));
};

/**
 * Format employment duration for display
 */
export const formatEmploymentDuration = (days: number): string => {
  const years = Math.floor(days / 365);
  const months = Math.floor((days % 365) / 30);

  if (years > 0) {
    return `${years} ${years === 1 ? "سنة" : "سنوات"}${
      months > 0 ? ` و ${months} شهر` : ""
    }`;
  }
  if (months > 0) {
    return `${months} ${months === 1 ? "شهر" : "شهور"}`;
  }
  return `${days} ${days === 1 ? "يوم" : "أيام"}`;
};

// ============= Salary Update DTO =============

/**
 * DTO for updating an employee's salary
 * Uses optimistic locking via version field to handle concurrent updates
 *
 * Optimistic Locking Flow:
 * 1. Frontend reads current version from employee.version
 * 2. User edits salary field and submits form
 * 3. Frontend sends PUT with version field
 * 4. Backend checks: if employee.version != dto.version → 409 Conflict error
 * 5. On conflict: User must refresh to get latest version and try again
 *
 * Benefits:
 * - No row-level locks needed in the database
 * - Better performance under high concurrency
 * - Simple to implement on frontend
 * - Clear feedback when concurrent update detected
 */
export interface UpdateSalaryDto {
  /**
   * New base salary amount
   * Must be greater than 0
   * Type: number (will be converted to DECIMAL(12,2) on backend)
   */
  baseSalary: number;

  /**
   * Currency code (optional, defaults to SAR)
   * ISO 4217 format (e.g., "SAR", "USD", "AED")
   * Only used if different from employee's current currency
   */
  currency?: string;

  /**
   * Reason for salary change
   * Optional but recommended for audit trail
   * Max length: 500 characters
   * Examples: "Annual performance raise", "Promotion", "Market adjustment"
   */
  reason?: string;

  /**
   * CRITICAL: Current version number from employee record
   * Must match backend version exactly or request will fail with 409 Conflict
   * This prevents overwriting salary changes made by other users
   *
   * Frontend Responsibility:
   * - Always read version from employee.version when loading form
   * - Always send current version with update request
   * - On 409 response: Show "Data changed, refresh required" message
   * - User must refresh page and try again with new version
   */
  version?: number;
  rowVersion?: number;
}

/**
 * Response DTO after successful salary update
 * Includes updated employee data and new version for next update
 */
export interface UpdateSalaryResponseDto {
  id: string;
  baseSalary: number;
  currency: string;
  version: number;
  lastSalaryUpdate: string; // ISO date string
  lastSalaryUpdateBy: string; // User ID
}

/**
 * Salary History Entity - Immutable audit trail of salary changes
 * Created automatically whenever salary is updated via UpdateEmployeeSalaryUseCase
 */
export interface SalaryHistoryEntity {
  id: string;
  employeeId: string;
  /**
   * Salary amount BEFORE the change
   */
  baseSalaryBefore: number;

  /**
   * Salary amount AFTER the change
   */
  baseSalaryAfter: number;

  /**
   * Absolute change in salary (After - Before)
   * Computed field: can be negative for salary reductions
   */
  changeAmount?: number;

  /**
   * Percentage change: ((After - Before) / Before) * 100
   * Computed field: allows comparing salary changes across different salary levels
   * Example: 10% increase regardless of base amount
   */
  changePercentage?: number;

  /**
   * Computed field: true if changeAmount > 0
   */
  isRaise?: boolean;

  /**
   * Reason provided by the user for the salary change
   * Optional, max 500 characters
   * Examples: "Annual review", "Promotion", "Market adjustment", "Cost of living adjustment"
   */
  reason?: string | null;

  /**
   * Source of the salary change - who/what initiated it
   * - MANUAL: Changed via payroll module by HR
   * - EMPLOYEE_UPDATE: Changed as part of employee record update
   * - BULK_UPDATE: Changed via bulk salary update operation
   * - MIGRATION: Changed during data migration
   * - SYSTEM: Changed by system (future use)
   */
  source: "MANUAL" | "EMPLOYEE_UPDATE" | "BULK_UPDATE" | "MIGRATION" | "SYSTEM";

  /**
   * When the salary change was made (ISO date string)
   */
  changedAt: string;

  /**
   * UUID of the user who made the salary change
   * Used for audit trail and permission tracking
   */
  changedBy: string;

  /**
   * User details (populated when including relations)
   * Contains firstName, lastName, email for display
   */
  changedByUser?: {
    id: string;
    firstName: string;
    lastName: string;
    email?: string;
  };

  /**
   * ISO date string when this history record was created
   */
  createdAt: string;
}
