param(
  [Parameter(Mandatory = $true)]
  [string]$EnvironmentName,

  [Parameter(Mandatory = $true)]
  [string]$BackendUrl,

  [Parameter(Mandatory = $false)]
  [string]$FrontendUrl = "",

  [switch]$SkipFrontend
)

$ErrorActionPreference = "Stop"

$root = Resolve-Path (Join-Path $PSScriptRoot "..\..")
$artifacts = Join-Path $root "release-artifacts"
if (-not (Test-Path $artifacts)) {
  New-Item -Path $artifacts -ItemType Directory | Out-Null
}

$timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
$safeEnv = ($EnvironmentName -replace "[^a-zA-Z0-9_-]", "_")

Write-Host "Running Phase 5 smoke for environment: $EnvironmentName" -ForegroundColor Cyan
Write-Host "Backend URL: $BackendUrl"
if ($SkipFrontend) {
  Write-Host "Frontend check: skipped"
} else {
  Write-Host "Frontend URL: $FrontendUrl"
}

$env:PHASE5_BACKEND_URL = $BackendUrl
if ($SkipFrontend) {
  $env:PHASE5_SKIP_FRONTEND = "true"
  Remove-Item Env:PHASE5_FRONTEND_URL -ErrorAction SilentlyContinue
} else {
  if ([string]::IsNullOrWhiteSpace($FrontendUrl)) {
    throw "FrontendUrl is required unless -SkipFrontend is provided."
  }
  $env:PHASE5_SKIP_FRONTEND = "false"
  $env:PHASE5_FRONTEND_URL = $FrontendUrl
}

try {
  & node (Join-Path $root "scripts\release\run-phase5-monitoring-smoke.mjs")
  $exitCode = $LASTEXITCODE
} finally {
  Remove-Item Env:PHASE5_BACKEND_URL -ErrorAction SilentlyContinue
  Remove-Item Env:PHASE5_FRONTEND_URL -ErrorAction SilentlyContinue
  Remove-Item Env:PHASE5_SKIP_FRONTEND -ErrorAction SilentlyContinue
}

$latestMd = Join-Path $artifacts "phase5-monitoring-smoke-latest.md"
$latestJson = Join-Path $artifacts "phase5-monitoring-smoke-latest.json"
$targetMd = Join-Path $artifacts "$safeEnv-phase5-smoke-$timestamp.md"
$targetJson = Join-Path $artifacts "$safeEnv-phase5-smoke-$timestamp.json"

if (Test-Path $latestMd) {
  Copy-Item $latestMd $targetMd -Force
}
if (Test-Path $latestJson) {
  Copy-Item $latestJson $targetJson -Force
}

$evidenceFile = Join-Path $artifacts "GO_LIVE_TARGET_EVIDENCE.md"
$reportLine = "- [$timestamp] $EnvironmentName => ExitCode=$exitCode, md=`"$targetMd`", json=`"$targetJson`""
if (-not (Test-Path $evidenceFile)) {
  @(
    "# Go-Live Target Evidence"
    ""
    "Generated by scripts/release/run-phase5-target.ps1"
    ""
    "## Runs"
    $reportLine
  ) | Set-Content -Path $evidenceFile -Encoding UTF8
} else {
  Add-Content -Path $evidenceFile -Value $reportLine
}

if ($exitCode -eq 0) {
  Write-Host "Phase 5 target smoke passed." -ForegroundColor Green
  Write-Host "Saved evidence:"
  Write-Host "  $targetMd"
  Write-Host "  $targetJson"
  exit 0
}

Write-Host "Phase 5 target smoke failed. Check report: $targetMd" -ForegroundColor Red
exit $exitCode
