/**
 * Sites Seed Data  LARGE DATASET
 * 62 construction sites across the Kingdom of Saudi Arabia
 */

import { PrismaClient, SiteStatus } from '@prisma/client';

type SiteDef = {
  name: string;
  code: string;
  city: string;
  state: string;
  address: string;
  postalCode: string;
  lat: number;
  lng: number;
  area: number;
  capacity: number;
  status: SiteStatus;
  contactPerson: string;
  contactPhone: string;
  contactEmail: string;
  description: string;
};

const siteDefs: SiteDef[] = [
  // الرياض (12 sites)
  {
    name: 'برج الأعمال المركزي',
    code: 'SITE-RYD-001',
    city: 'الرياض',
    state: 'منطقة الرياض',
    address: 'طريق الملك فهد حي العليا الرياض',
    postalCode: '11564',
    lat: 24.7136,
    lng: 46.6753,
    area: 50000,
    capacity: 200,
    status: SiteStatus.ACTIVE,
    contactPerson: 'عبدالرحمن العتيبي',
    contactPhone: '+201501111101',
    contactEmail: 'ryd01@erp-construction.sa',
    description: 'بناء برج تجاري مكون من 45 طابقا في قلب شارع العليا بالرياض',
  },
  {
    name: 'مجمع أبراج الملك سلمان',
    code: 'SITE-RYD-002',
    city: 'الرياض',
    state: 'منطقة الرياض',
    address: 'شارع الدائري الشرقي أمام مجمع الملك فهد الطبي',
    postalCode: '11461',
    lat: 24.7306,
    lng: 46.5762,
    area: 80000,
    capacity: 350,
    status: SiteStatus.ACTIVE,
    contactPerson: 'فهاد العمري',
    contactPhone: '+201501111102',
    contactEmail: 'ryd02@erp-construction.sa',
    description: 'مجمع سكني متكامل يضم وحدات سكنية فاخرة ومرافق خدمية متكاملة',
  },
  {
    name: 'مبنى مجمع الوزارات الجديد',
    code: 'SITE-RYD-003',
    city: 'الرياض',
    state: 'منطقة الرياض',
    address: 'شارع عبدالله بن هذيل قرب شارع الملك عبدالله',
    postalCode: '12211',
    lat: 24.7853,
    lng: 46.6344,
    area: 60000,
    capacity: 400,
    status: SiteStatus.ACTIVE,
    contactPerson: 'نايف القحطاني',
    contactPhone: '+201501111103',
    contactEmail: 'ryd03@erp-construction.sa',
    description: 'مجمع حكومي يضم عدة وزارات تحت سقف واحد وفق معايير البناء الأخضر',
  },
  {
    name: 'منشآت مصرف الإنماء الجديدة',
    code: 'SITE-RYD-004',
    city: 'الرياض',
    state: 'منطقة الرياض',
    address: 'شارع العروبة قرب شارع الأمير سلطان',
    postalCode: '11176',
    lat: 24.6877,
    lng: 46.7219,
    area: 35000,
    capacity: 280,
    status: SiteStatus.ACTIVE,
    contactPerson: 'سالم الزهراني',
    contactPhone: '+201501111104',
    contactEmail: 'ryd04@erp-construction.sa',
    description: 'مبنى مقر رئيسي لمصرف يستوعب 600 موظف في قلب الرياض المالي',
  },
  {
    name: 'أم الحمام السكني الكبير',
    code: 'SITE-RYD-005',
    city: 'الرياض',
    state: 'منطقة الرياض',
    address: 'طريق الدائري الشمالي الخارجي حي أم الحمام',
    postalCode: '11621',
    lat: 24.8231,
    lng: 46.7112,
    area: 120000,
    capacity: 500,
    status: SiteStatus.ACTIVE,
    contactPerson: 'ماجد الدوسري',
    contactPhone: '+201501111105',
    contactEmail: 'ryd05@erp-construction.sa',
    description: 'مشروع تطوير سكني يضم أكثر من 800 وحدة سكنية متنوعة الأحجام',
  },
  {
    name: 'مشروع حي المطار الجديد',
    code: 'SITE-RYD-006',
    city: 'الرياض',
    state: 'منطقة الرياض',
    address: 'شارع الملك عبدالعزيز قرب مطار الملك خالد',
    postalCode: '13316',
    lat: 24.859,
    lng: 46.612,
    area: 45000,
    capacity: 180,
    status: SiteStatus.UNDER_PREPARATION,
    contactPerson: 'عمر الشمري',
    contactPhone: '+201501111106',
    contactEmail: 'ryd06@erp-construction.sa',
    description: 'تطوير البنية التحتية لحي تجاري جديد بالقرب من منطقة المطار',
  },
  {
    name: 'مبنى مركز الابتكار والتقنية',
    code: 'SITE-RYD-007',
    city: 'الرياض',
    state: 'منطقة الرياض',
    address: 'طريق التخصصي قرب المدينة الطبية',
    postalCode: '11422',
    lat: 24.6743,
    lng: 46.6892,
    area: 28000,
    capacity: 220,
    status: SiteStatus.ACTIVE,
    contactPerson: 'فيصل المطيري',
    contactPhone: '+201501111107',
    contactEmail: 'ryd07@erp-construction.sa',
    description: 'مبنى متعدد الاستخدامات يضم دورا للشركات التقنية والمختبرات البحثية',
  },
  {
    name: 'منطقة اليوسفية الصناعية',
    code: 'SITE-RYD-008',
    city: 'الرياض',
    state: 'منطقة الرياض',
    address: 'المنطقة الصناعية الأولى طريق المدينة المنورة',
    postalCode: '11452',
    lat: 24.5981,
    lng: 46.8204,
    area: 200000,
    capacity: 150,
    status: SiteStatus.ACTIVE,
    contactPerson: 'عمر العنزي',
    contactPhone: '+201501111108',
    contactEmail: 'ryd08@erp-construction.sa',
    description: 'تطوير المنطقة الصناعية الأولى وتحديث البنية التحتية ومنشآت التصنيع',
  },
  {
    name: 'مشروع درة الرياض السكني',
    code: 'SITE-RYD-009',
    city: 'الرياض',
    state: 'منطقة الرياض',
    address: 'شارع السلام الشمالي قرب حي الملقا',
    postalCode: '13326',
    lat: 24.9041,
    lng: 46.6388,
    area: 90000,
    capacity: 300,
    status: SiteStatus.ACTIVE,
    contactPerson: 'خالد الغامدي',
    contactPhone: '+201501111109',
    contactEmail: 'ryd09@erp-construction.sa',
    description: 'مشروع سكني راق يضم 250 فيلا في منطقة الملقا الهادئة',
  },
  {
    name: 'مبنى مجمع الأمير محمد الصحي',
    code: 'SITE-RYD-010',
    city: 'الرياض',
    state: 'منطقة الرياض',
    address: 'طريق الدائري الشرقي قرب مستشفى الملك فيصل',
    postalCode: '11692',
    lat: 24.9632,
    lng: 46.7021,
    area: 40000,
    capacity: 80,
    status: SiteStatus.UNDER_PREPARATION,
    contactPerson: 'بدر نجدي',
    contactPhone: '+201501111110',
    contactEmail: 'ryd10@erp-construction.sa',
    description: 'مجمع طبي متكامل يضم عيادات تخصصية بطاقة استيعابية 500 مريض يوميا',
  },
  {
    name: 'مجمع سدير للصناعات البتروكيماوية',
    code: 'SITE-RYD-011',
    city: 'الرياض',
    state: 'منطقة الرياض',
    address: 'المنطقة الصناعية الثانية شمال الرياض طريق سدير',
    postalCode: '12462',
    lat: 24.5621,
    lng: 46.7841,
    area: 150000,
    capacity: 200,
    status: SiteStatus.ACTIVE,
    contactPerson: 'عبدالله الرشيدي',
    contactPhone: '+201501111111',
    contactEmail: 'ryd11@erp-construction.sa',
    description: 'تطوير منشآت صناعية متكاملة للصناعات البتروكيماوية والتحويلية',
  },
  {
    name: 'مبنى حي نزال الرياض',
    code: 'SITE-RYD-012',
    city: 'الرياض',
    state: 'منطقة الرياض',
    address: 'شارع التحلية قرب طريق الملك فهد',
    postalCode: '11591',
    lat: 24.7001,
    lng: 46.7312,
    area: 55000,
    capacity: 260,
    status: SiteStatus.INACTIVE,
    contactPerson: 'علاء الشهراني',
    contactPhone: '+201501111112',
    contactEmail: 'ryd12@erp-construction.sa',
    description: 'مبنى تجاري سكني متعدد الطوابع يستوعب مكاتب للإيجار بمساحة 40,000 متر',
  },
  // جدة (10 sites)
  {
    name: 'مشروع مول جدة الجديد شمال جدة',
    code: 'SITE-JED-001',
    city: 'جدة',
    state: 'منطقة مكة المكرمة',
    address: 'طريق الكورنيش الشمالي حي الشاطئ',
    postalCode: '23212',
    lat: 21.5433,
    lng: 39.1728,
    area: 75000,
    capacity: 300,
    status: SiteStatus.ACTIVE,
    contactPerson: 'تركي الجهني',
    contactPhone: '+201502211101',
    contactEmail: 'jed01@erp-construction.sa',
    description: 'إنشاء مركز تجاري كبير على كورنيش جدة بمساحة 120 ألف متر و50 متجرا',
  },
  {
    name: 'برج جدة التجاري',
    code: 'SITE-JED-002',
    city: 'جدة',
    state: 'منطقة مكة المكرمة',
    address: 'شارع الأمير محمد بن عبدالعزيز قرب الميناء',
    postalCode: '21441',
    lat: 21.4961,
    lng: 39.1845,
    area: 20000,
    capacity: 180,
    status: SiteStatus.ACTIVE,
    contactPerson: 'رائد مرعي',
    contactPhone: '+201502211102',
    contactEmail: 'jed02@erp-construction.sa',
    description: 'برج تجاري يتكون من 35 طابقا يطل مباشرة على ميناء جدة الإسلامي',
  },
  {
    name: 'مبنى مول الوردة جدة',
    code: 'SITE-JED-003',
    city: 'جدة',
    state: 'منطقة مكة المكرمة',
    address: 'شارع الستين قرب مستشفى الحمدانية',
    postalCode: '23434',
    lat: 21.5701,
    lng: 39.1561,
    area: 32000,
    capacity: 240,
    status: SiteStatus.ACTIVE,
    contactPerson: 'هاني صبري',
    contactPhone: '+201502211103',
    contactEmail: 'jed03@erp-construction.sa',
    description: 'مبنى تجاري من 45 طابقا يضم محال تجارية ومكاتب إدارية',
  },
  {
    name: 'مشروع توسعة ميناء جدة',
    code: 'SITE-JED-004',
    city: 'جدة',
    state: 'منطقة مكة المكرمة',
    address: 'طريق الملك عبدالعزيز ميناء جدة الإسلامي',
    postalCode: '21421',
    lat: 21.6796,
    lng: 39.1565,
    area: 500000,
    capacity: 600,
    status: SiteStatus.ACTIVE,
    contactPerson: 'وليد رضوان',
    contactPhone: '+201502211104',
    contactEmail: 'jed04@erp-construction.sa',
    description: 'توسعة ميناء جدة الإسلامي ورفع طاقته الاستيعابية للبضائع والحاويات',
  },
  {
    name: 'مبنى مركز الخزامى التجاري',
    code: 'SITE-JED-005',
    city: 'جدة',
    state: 'منطقة مكة المكرمة',
    address: 'شارع التحلية قرب منطقة البلد التاريخي',
    postalCode: '22231',
    lat: 21.4812,
    lng: 39.1971,
    area: 65000,
    capacity: 320,
    status: SiteStatus.UNDER_PREPARATION,
    contactPerson: 'سامي خوجه',
    contactPhone: '+201502211105',
    contactEmail: 'jed05@erp-construction.sa',
    description: 'مشروع مركز أعمال متكامل في قلب جدة التجارية بالقرب من مناطق التراث',
  },
  {
    name: 'مبنى مكتب المركز المالي',
    code: 'SITE-JED-006',
    city: 'جدة',
    state: 'منطقة مكة المكرمة',
    address: 'المنطقة الصناعية الثانية حي المطار',
    postalCode: '21414',
    lat: 21.6201,
    lng: 39.1084,
    area: 90000,
    capacity: 120,
    status: SiteStatus.ACTIVE,
    contactPerson: 'لؤي سرحان',
    contactPhone: '+201502211106',
    contactEmail: 'jed06@erp-construction.sa',
    description: 'مبنى مركز مالي يضم مكاتب البنوك والمؤسسات المالية والمصرفية',
  },
  {
    name: 'منطقة مدينة المعرفة الاقتصادية',
    code: 'SITE-JED-007',
    city: 'جدة',
    state: 'منطقة مكة المكرمة',
    address: 'شارع أبحر الشمالية',
    postalCode: '23352',
    lat: 21.7012,
    lng: 39.1319,
    area: 110000,
    capacity: 400,
    status: SiteStatus.ACTIVE,
    contactPerson: 'أمير البركاتي',
    contactPhone: '+201502211107',
    contactEmail: 'jed07@erp-construction.sa',
    description: 'مدينة معرفة متكاملة تضم جامعات ومراكز بحثية وشركات تقنية',
  },
  {
    name: 'مبنى مركز الشعلة التجاري',
    code: 'SITE-JED-008',
    city: 'جدة',
    state: 'منطقة مكة المكرمة',
    address: 'شارع الستين قرب مستشفى بختيار',
    postalCode: '23631',
    lat: 21.5219,
    lng: 39.2041,
    area: 18000,
    capacity: 150,
    status: SiteStatus.UNDER_PREPARATION,
    contactPerson: 'سعد صالح',
    contactPhone: '+201502211108',
    contactEmail: 'jed08@erp-construction.sa',
    description: 'مركز تجاري يضم متاجر التجزئة ومطاعم ومرافق ترفيهية للأسرة',
  },
  {
    name: 'مشروع مطار الملك عبدالعزيز الدولي',
    code: 'SITE-JED-009',
    city: 'جدة',
    state: 'منطقة مكة المكرمة',
    address: 'طريق مكة المكرمة',
    postalCode: '25716',
    lat: 22.9801,
    lng: 38.9562,
    area: 1000000,
    capacity: 800,
    status: SiteStatus.ACTIVE,
    contactPerson: 'ياسر الغامدي',
    contactPhone: '+201502211109',
    contactEmail: 'jed09@erp-construction.sa',
    description: 'توسعة مطار الملك عبدالعزيز الدولي لزيادة الطاقة الاستيعابية للحجاج',
  },
  {
    name: 'مرسى البحر الأحمر للتطوير',
    code: 'SITE-JED-010',
    city: 'جدة',
    state: 'منطقة مكة المكرمة',
    address: 'شارع أبحر الجنوبية قرب طريق الميناء',
    postalCode: '23324',
    lat: 21.6312,
    lng: 39.1728,
    area: 140000,
    capacity: 550,
    status: SiteStatus.ACTIVE,
    contactPerson: 'محمد الزبيدي',
    contactPhone: '+201502211110',
    contactEmail: 'jed10@erp-construction.sa',
    description: 'مشروع مرسى وإنشاءات ساحلية ضمن تطوير منطقة أبحر الجنوبية الترفيهية',
  },
  // المنطقة الشرقية (7 sites)
  {
    name: 'المستودعات الصناعية دمام',
    code: 'SITE-DMM-001',
    city: 'الدمام',
    state: 'المنطقة الشرقية',
    address: 'المنطقة الصناعية الثانية طريق الدمام الصناعي',
    postalCode: '32241',
    lat: 26.4207,
    lng: 50.0888,
    area: 120000,
    capacity: 150,
    status: SiteStatus.ACTIVE,
    contactPerson: 'وليد حمدان',
    contactPhone: '+201503311101',
    contactEmail: 'dmm01@erp-construction.sa',
    description: 'إنشاء مستودعات صناعية ضخمة بمساحة 120,000 متر لخدمة المنطقة الشرقية',
  },
  {
    name: 'مشروع طريق الخبر الساحلي',
    code: 'SITE-KHB-001',
    city: 'الخبر',
    state: 'المنطقة الشرقية',
    address: 'طريق الكورنيش الشمالي حي العقربية',
    postalCode: '34446',
    lat: 26.2948,
    lng: 50.208,
    area: 60000,
    capacity: 220,
    status: SiteStatus.ACTIVE,
    contactPerson: 'عمر الحربي',
    contactPhone: '+201508888801',
    contactEmail: 'khb01@erp-construction.sa',
    description: 'تطوير الطريق الساحلي في الخبر وإنشاء منشآت ترفيهية وتجارية على الكورنيش',
  },
  {
    name: 'برج الظهران التكنولوجي',
    code: 'SITE-DHR-001',
    city: 'الظهران',
    state: 'المنطقة الشرقية',
    address: 'طريق الملك فيصل وسط الظهران',
    postalCode: '31952',
    lat: 26.3017,
    lng: 50.1567,
    area: 25000,
    capacity: 180,
    status: SiteStatus.ACTIVE,
    contactPerson: 'هاني العوضي',
    contactPhone: '+201503311103',
    contactEmail: 'dhr01@erp-construction.sa',
    description: 'مبنى مكتبي ذكي بمواصفات LEED للشركات التقنية والبترولية في الظهران',
  },
  {
    name: 'مبنى تطوير القطيف التاريخي',
    code: 'SITE-QTF-001',
    city: 'القطيف',
    state: 'المنطقة الشرقية',
    address: 'شارع الحزام قرب البلدة القديمة القطيف',
    postalCode: '31911',
    lat: 26.5236,
    lng: 50.0095,
    area: 30000,
    capacity: 200,
    status: SiteStatus.ACTIVE,
    contactPerson: 'علي قاسم',
    contactPhone: '+201503311104',
    contactEmail: 'qtf01@erp-construction.sa',
    description: 'ترميم وتطوير منطقة البلدة القديمة بالقطيف بطاقة استيعابية 400 زائر يوميا',
  },
  {
    name: 'مشروع المجمع البتروكيماوي الجبيل',
    code: 'SITE-JBL-001',
    city: 'الجبيل',
    state: 'المنطقة الشرقية',
    address: 'المنطقة الصناعية الأولى الجبيل الصناعية',
    postalCode: '35718',
    lat: 27.0046,
    lng: 49.6577,
    area: 300000,
    capacity: 400,
    status: SiteStatus.ACTIVE,
    contactPerson: 'أحمد الصبيحي',
    contactPhone: '+201503311105',
    contactEmail: 'jbl01@erp-construction.sa',
    description: 'توسعة مجمع البتروكيماويات في المدينة الصناعية بالجبيل المرحلة الثالثة',
  },
  {
    name: 'مجمع الأحساء التاريخي والثقافي',
    code: 'SITE-AHS-001',
    city: 'الأحساء',
    state: 'المنطقة الشرقية',
    address: 'طريق الملك عبدالله قلب الهفوف',
    postalCode: '31982',
    lat: 25.3719,
    lng: 49.5878,
    area: 80000,
    capacity: 600,
    status: SiteStatus.ACTIVE,
    contactPerson: 'عبدالكريم الموسى',
    contactPhone: '+201503311106',
    contactEmail: 'ahs01@erp-construction.sa',
    description: 'ترميم المناطق التراثية في الأحساء وتطويرها ضمن مشروع اليونسكو للتراث',
  },
  {
    name: 'منطقة ميناء الدمام التوسعية',
    code: 'SITE-DMM-002',
    city: 'الدمام',
    state: 'المنطقة الشرقية',
    address: 'ميناء الملك عبدالعزيز الرصيف السابع',
    postalCode: '32214',
    lat: 26.4681,
    lng: 50.1621,
    area: 450000,
    capacity: 350,
    status: SiteStatus.UNDER_PREPARATION,
    contactPerson: 'فاروق سالم',
    contactPhone: '+201503311107',
    contactEmail: 'dmm02@erp-construction.sa',
    description: 'توسعة ميناء الملك عبدالعزيز بإضافة 7 أرصفة جديدة وزيادة الطاقة الشحنية',
  },
  // مكة المكرمة (5 sites)
  {
    name: 'مبنى المسجد الحرام للخدمات',
    code: 'SITE-MKH-001',
    city: 'مكة المكرمة',
    state: 'منطقة مكة المكرمة',
    address: 'شارع إبراهيم خليل',
    postalCode: '24231',
    lat: 21.4225,
    lng: 39.8262,
    area: 30000,
    capacity: 180,
    status: SiteStatus.UNDER_PREPARATION,
    contactPerson: 'أحمد العسيري',
    contactPhone: '+201504444401',
    contactEmail: 'mkh01@erp-construction.sa',
    description: 'إنشاء مبنى خدمات متكامل لدعم زوار المسجد الحرام وخدمة ضيوف الرحمن',
  },
  {
    name: 'مبنى أبراج البيت مكة',
    code: 'SITE-MKH-002',
    city: 'مكة المكرمة',
    state: 'منطقة مكة المكرمة',
    address: 'شارع أجياد قرب المسجد الحرام',
    postalCode: '24242',
    lat: 21.4121,
    lng: 39.8236,
    area: 40000,
    capacity: 500,
    status: SiteStatus.ACTIVE,
    contactPerson: 'خالد العسيري',
    contactPhone: '+201504444402',
    contactEmail: 'mkh02@erp-construction.sa',
    description: 'مبنى خدمي يضم 1200 غرفة لاستيعاب الحجاج والمعتمرين قرب المسجد الحرام',
  },
  {
    name: 'مبنى خدمات الحجاج والمعتمرين',
    code: 'SITE-MKH-003',
    city: 'مكة المكرمة',
    state: 'منطقة مكة المكرمة',
    address: 'المنطقة المركزية شارع المعابدة',
    postalCode: '24251',
    lat: 21.4382,
    lng: 39.8249,
    area: 15000,
    capacity: 120,
    status: SiteStatus.ACTIVE,
    contactPerson: 'عبدالكريم الغامدي',
    contactPhone: '+201504444403',
    contactEmail: 'mkh03@erp-construction.sa',
    description: 'مركز خدمات شامل للحجاج يوفر الإرشاد والرعاية الصحية ومتطلبات النسك',
  },
  {
    name: 'مبنى مركز مكة التجاري',
    code: 'SITE-MKH-004',
    city: 'مكة المكرمة',
    state: 'منطقة مكة المكرمة',
    address: 'شارع أجياد قرب طريق الملك فهد',
    postalCode: '24311',
    lat: 21.3898,
    lng: 39.8524,
    area: 55000,
    capacity: 280,
    status: SiteStatus.ACTIVE,
    contactPerson: 'عادل النفيعي',
    contactPhone: '+201504444404',
    contactEmail: 'mkh04@erp-construction.sa',
    description: 'مبنى تجاري يضم 350 محلا يخدم زوار مكة المكرمة من حجاج ومعتمرين',
  },
  {
    name: 'مشروع توسعة المسجد الحرام',
    code: 'SITE-MKH-005',
    city: 'مكة المكرمة',
    state: 'منطقة مكة المكرمة',
    address: 'المنطقة المركزية حول المسجد الحرام',
    postalCode: '24282',
    lat: 21.4601,
    lng: 39.7912,
    area: 600000,
    capacity: 200,
    status: SiteStatus.UNDER_PREPARATION,
    contactPerson: 'بندر القرشي',
    contactPhone: '+201504444405',
    contactEmail: 'mkh05@erp-construction.sa',
    description: 'إضافة 40 ألف متر إلى المسجد الحرام لاستيعاب الأعداد المتزايدة من الحجاج',
  },
  // المدينة المنورة & ينبع (4 sites)
  {
    name: 'مشروع طريق الهجرة المدينة المنورة',
    code: 'SITE-MDN-001',
    city: 'المدينة المنورة',
    state: 'منطقة المدينة المنورة',
    address: 'شارع السلام الجنوبي قرب المسجد النبوي',
    postalCode: '42311',
    lat: 24.4672,
    lng: 39.6111,
    area: 85000,
    capacity: 250,
    status: SiteStatus.ACTIVE,
    contactPerson: 'أحمد الحربي',
    contactPhone: '+201505551101',
    contactEmail: 'mdn01@erp-construction.sa',
    description: 'مبنى فندقي ضخم بمساحة كبيرة قريب من المسجد النبوي الشريف',
  },
  {
    name: 'مبنى مركز مدينة السلام',
    code: 'SITE-MDN-002',
    city: 'المدينة المنورة',
    state: 'منطقة المدينة المنورة',
    address: 'جادة المحمدية قرب محطة الحرمين',
    postalCode: '42312',
    lat: 24.4672,
    lng: 39.6211,
    area: 22000,
    capacity: 350,
    status: SiteStatus.ACTIVE,
    contactPerson: 'أحمد الحربي',
    contactPhone: '+201505551102',
    contactEmail: 'mdn02@erp-construction.sa',
    description: 'مبنى تجاري من 5 طوابق يضم 800 محل تجاري بالقرب من المسجد النبوي',
  },
  {
    name: 'المصافي البتروكيماوية ينبع',
    code: 'SITE-YNB-001',
    city: 'ينبع',
    state: 'منطقة المدينة المنورة',
    address: 'طريق الملك عبدالله ميناء ينبع الصناعي',
    postalCode: '46481',
    lat: 24.0875,
    lng: 38.0585,
    area: 250000,
    capacity: 300,
    status: SiteStatus.ACTIVE,
    contactPerson: 'علي الزهراني',
    contactPhone: '+201505551103',
    contactEmail: 'ynb01@erp-construction.sa',
    description: 'توسعة المجمع البتروكيماوي في ينبع الصناعية ورفع الطاقة الإنتاجية',
  },
  {
    name: 'مشروع ميناء ينبع التجاري',
    code: 'SITE-YNB-002',
    city: 'ينبع',
    state: 'منطقة المدينة المنورة',
    address: 'منطقة الميناء التجاري طريق ينبع',
    postalCode: '46482',
    lat: 24.2011,
    lng: 37.9231,
    area: 400000,
    capacity: 120,
    status: SiteStatus.UNDER_PREPARATION,
    contactPerson: 'فهد العتيبي',
    contactPhone: '+201505551104',
    contactEmail: 'ynb02@erp-construction.sa',
    description: 'توسعة 60 ألف متر مربع إلى ميناء ينبع لاستيعاب حاويات البضائع',
  },
  // منطقة عسير (3 sites)
  {
    name: 'منطقة عسير السياحية الجديدة',
    code: 'SITE-ABH-001',
    city: 'أبها',
    state: 'منطقة عسير',
    address: 'طريق الملك فيصل قرب منتزه السودة',
    postalCode: '62521',
    lat: 18.2164,
    lng: 42.5053,
    area: 45000,
    capacity: 120,
    status: SiteStatus.ACTIVE,
    contactPerson: 'عبدالعزيز الشهراني',
    contactPhone: '+201507661101',
    contactEmail: 'abh01@erp-construction.sa',
    description: 'تطوير منطقة سياحية متكاملة في أبها تشمل فنادق ومنتجعات جبلية فاخرة',
  },
  {
    name: 'مشروع قمة سروات أبها الكبير',
    code: 'SITE-ABH-002',
    city: 'أبها',
    state: 'منطقة عسير',
    address: 'طريق عسير قرب قمة السودة',
    postalCode: '61411',
    lat: 18.2403,
    lng: 42.6562,
    area: 200000,
    capacity: 400,
    status: SiteStatus.ACTIVE,
    contactPerson: 'هشام الغامدي',
    contactPhone: '+201507661102',
    contactEmail: 'abh02@erp-construction.sa',
    description: 'مشروع مدينة جبلية متكاملة تراعي الطابع البيئي والسياحي لمنطقة عسير',
  },
  {
    name: 'مبنى مركز بيشة الإداري',
    code: 'SITE-ABH-003',
    city: 'بيشة',
    state: 'منطقة عسير',
    address: 'شارع الملك سلمان وسط مدينة بيشة',
    postalCode: '63742',
    lat: 18.5431,
    lng: 42.0321,
    area: 20000,
    capacity: 80,
    status: SiteStatus.UNDER_PREPARATION,
    contactPerson: 'نجيب الأسمري',
    contactPhone: '+201507661103',
    contactEmail: 'abh03@erp-construction.sa',
    description: 'مبنى حكومي متعدد الأغراض يضم مكاتب إدارية ومحاكم ومرافق خدمية',
  },
  // تبوك (3 sites)
  {
    name: 'مشروع البنية التحتية لنيوم تبوك',
    code: 'SITE-TBK-001',
    city: 'تبوك',
    state: 'منطقة تبوك',
    address: 'شارع الملك عبدالله شمال تبوك',
    postalCode: '71491',
    lat: 28.3998,
    lng: 36.5782,
    area: 200000,
    capacity: 100,
    status: SiteStatus.UNDER_PREPARATION,
    contactPerson: 'عمر الحربي',
    contactPhone: '+201507771101',
    contactEmail: 'tbk01@erp-construction.sa',
    description: 'إنشاء البنية التحتية لدعم مدينة نيوم العملاقة الموجودة شمال تبوك',
  },
  {
    name: 'منتجع خليج العقبة الساحلي',
    code: 'SITE-TBK-002',
    city: 'تبوك',
    state: 'منطقة تبوك',
    address: 'ساحل خليج العقبة طريق الشرم',
    postalCode: '77731',
    lat: 29.1841,
    lng: 34.9761,
    area: 2000000,
    capacity: 1000,
    status: SiteStatus.ACTIVE,
    contactPerson: 'فهاد الشمري',
    contactPhone: '+201507771102',
    contactEmail: 'tbk02@erp-construction.sa',
    description: 'منتجع سياحي شامل على شاطئ خليج العقبة ضمن مشاريع تطوير ساحل البحر الأحمر',
  },
  {
    name: 'مبنى فندق خليج تبوك التجاري',
    code: 'SITE-TBK-003',
    city: 'تبوك',
    state: 'منطقة تبوك',
    address: 'شارع الملك فهد وسط مدينة تبوك',
    postalCode: '71411',
    lat: 28.4001,
    lng: 37.1234,
    area: 500000,
    capacity: 80,
    status: SiteStatus.ACTIVE,
    contactPerson: 'خالد الرشيدي',
    contactPhone: '+201507771103',
    contactEmail: 'tbk03@erp-construction.sa',
    description: 'مجمع فندقي يضم 1,000 غرفة لخدمة السياح والزائرين لمنطقة تبوك',
  },
  // القصيم / بريدة (3 sites)
  {
    name: 'مبنى مركز التجارة بريدة القصيم',
    code: 'SITE-QSM-001',
    city: 'بريدة',
    state: 'منطقة القصيم',
    address: 'طريق الملك عبدالعزيز الجنوبي حي المربع',
    postalCode: '52382',
    lat: 26.3293,
    lng: 43.9726,
    area: 40000,
    capacity: 260,
    status: SiteStatus.ACTIVE,
    contactPerson: 'وليد الرشيد',
    contactPhone: '+201503881101',
    contactEmail: 'qsm01@erp-construction.sa',
    description: 'مجمع تجاري يستوعب 500 محل بالقصيم وينشط الحركة التجارية في بريدة',
  },
  {
    name: 'مشروع طريق القصيم الزراعي',
    code: 'SITE-QSM-002',
    city: 'بريدة',
    state: 'منطقة القصيم',
    address: 'الطريق الإقليمي الشمالي للقصيم الزراعي',
    postalCode: '52391',
    lat: 26.3501,
    lng: 43.9512,
    area: 180000,
    capacity: 200,
    status: SiteStatus.ACTIVE,
    contactPerson: 'عمر الزهراني',
    contactPhone: '+201503881102',
    contactEmail: 'qsm02@erp-construction.sa',
    description: 'تطوير شبكة الطرق الزراعية بالقصيم لخدمة المزارع والمجمعات الزراعية',
  },
  {
    name: 'منطقة عنيزة الصناعية',
    code: 'SITE-QSM-003',
    city: 'عنيزة',
    state: 'منطقة القصيم',
    address: 'شارع الملك فهد قرب منفذ عنيزة',
    postalCode: '56316',
    lat: 26.1018,
    lng: 43.9924,
    area: 50000,
    capacity: 150,
    status: SiteStatus.UNDER_PREPARATION,
    contactPerson: 'خالد العنزي',
    contactPhone: '+201503881103',
    contactEmail: 'qsm03@erp-construction.sa',
    description: 'إنشاء منطقة صناعية جديدة في عنيزة تستوعب 120 مصنعا بمختلف الأحجام',
  },
  // الطائف (3 sites)
  {
    name: 'منشآت حديقة الطائف الجديدة',
    code: 'SITE-TAF-001',
    city: 'الطائف',
    state: 'منطقة مكة المكرمة',
    address: 'طريق الملك عبدالله حي أم العراد',
    postalCode: '26544',
    lat: 21.3591,
    lng: 40.5042,
    area: 75000,
    capacity: 200,
    status: SiteStatus.ACTIVE,
    contactPerson: 'فواز الشهراني',
    contactPhone: '+201502771101',
    contactEmail: 'taf01@erp-construction.sa',
    description: 'إنشاء حديقة عامة وملاعب رياضية ومنتزهات ضمن تطوير الطائف السياحي',
  },
  {
    name: 'مبنى مول الطائف التجاري الجديد',
    code: 'SITE-TAF-002',
    city: 'الطائف',
    state: 'منطقة مكة المكرمة',
    address: 'شارع الحضارة قرب حي الشهداء',
    postalCode: '26521',
    lat: 21.2703,
    lng: 40.4195,
    area: 30000,
    capacity: 180,
    status: SiteStatus.ACTIVE,
    contactPerson: 'ماجد الزهراني',
    contactPhone: '+201502771102',
    contactEmail: 'taf02@erp-construction.sa',
    description: 'مبنى مول تجاري جديد ضمن تطوير منطقة الطائف السياحية والترفيهية',
  },
  {
    name: 'مبنى مركز الطائف الصحي الجديد',
    code: 'SITE-TAF-003',
    city: 'الطائف',
    state: 'منطقة مكة المكرمة',
    address: 'طريق الملك فيصل حي السلامة',
    postalCode: '26571',
    lat: 21.4843,
    lng: 40.5441,
    area: 300000,
    capacity: 300,
    status: SiteStatus.UNDER_PREPARATION,
    contactPerson: 'فارس الغامدي',
    contactPhone: '+201502771103',
    contactEmail: 'taf03@erp-construction.sa',
    description: 'مجمع صحي متكامل يشمل مستشفى 5 نجوم ومراكز رعاية متخصصة بالطائف',
  },
  // جيزان (2 sites)
  {
    name: 'مشروع ميناء جيزان الصناعي الكبير',
    code: 'SITE-JZN-001',
    city: 'جيزان',
    state: 'منطقة جيزان',
    address: 'منطقة الميناء التجاري طريق الكورنيش',
    postalCode: '82724',
    lat: 16.8892,
    lng: 42.5701,
    area: 300000,
    capacity: 350,
    status: SiteStatus.ACTIVE,
    contactPerson: 'أحمد العمري',
    contactPhone: '+201507191101',
    contactEmail: 'jzn01@erp-construction.sa',
    description: 'توسعة ميناء جيزان الصناعي وتحديث المنطقة اللوجستية وزيادة الطاقة الاستيعابية',
  },
  {
    name: 'مشروع طريق جيزان الاستراتيجي',
    code: 'SITE-JZN-002',
    city: 'جيزان',
    state: 'منطقة جيزان',
    address: 'المنطقة الاقتصادية جيزان شارع الملك عبدالله',
    postalCode: '82732',
    lat: 16.9501,
    lng: 42.4821,
    area: 1200000,
    capacity: 700,
    status: SiteStatus.ACTIVE,
    contactPerson: 'نايف فيفا',
    contactPhone: '+201507191102',
    contactEmail: 'jzn02@erp-construction.sa',
    description:
      'تطوير الطريق الاستراتيجي في المنطقة الاقتصادية بجيزان وتهيئة البنية التحتية اللازمة',
  },
  // نجران (2 sites)
  {
    name: 'موقع نجران الصناعي الكبير',
    code: 'SITE-NJR-001',
    city: 'نجران',
    state: 'منطقة نجران',
    address: 'طريق الملك عبدالله حي النهضة الصناعية',
    postalCode: '66462',
    lat: 17.6112,
    lng: 44.4195,
    area: 120000,
    capacity: 150,
    status: SiteStatus.ACTIVE,
    contactPerson: 'فيصل القحطاني',
    contactPhone: '+201507551101',
    contactEmail: 'njr01@erp-construction.sa',
    description: 'تطوير المنطقة الصناعية في نجران وإنشاء مصانع للصناعات التحويلية',
  },
  {
    name: 'مشروع سد نجران الصحراوي الكبير',
    code: 'SITE-NJR-002',
    city: 'نجران',
    state: 'منطقة نجران',
    address: 'طريق سد نجران الرئيسي وادي نجران',
    postalCode: '66432',
    lat: 18.0012,
    lng: 44.3291,
    area: 400000,
    capacity: 80,
    status: SiteStatus.UNDER_PREPARATION,
    contactPerson: 'عمر العمري',
    contactPhone: '+201507551102',
    contactEmail: 'njr02@erp-construction.sa',
    description: 'مشروع سد نجران الجديد بطاقة تخزينية 500 مليون متر مكعب لدعم المياه',
  },
  // حائل (2 sites)
  {
    name: 'مزرعة حائل للتنمية الزراعية الكبرى',
    code: 'SITE-HAL-001',
    city: 'حائل',
    state: 'منطقة حائل',
    address: 'شارع الزراعة قرب طريق حائل الدولي',
    postalCode: '81622',
    lat: 27.5219,
    lng: 41.6832,
    area: 70000,
    capacity: 280,
    status: SiteStatus.ACTIVE,
    contactPerson: 'فيصل القحطاني',
    contactPhone: '+201506641101',
    contactEmail: 'hal01@erp-construction.sa',
    description: 'مشروع تنمية زراعية لزراعة 500 فدان في منطقة حائل لتحقيق الأمن الغذائي',
  },
  {
    name: 'مجمع حائل للصناعات الغذائية',
    code: 'SITE-HAL-002',
    city: 'حائل',
    state: 'منطقة حائل',
    address: 'طريق حائل خميس مشيط قرب المنطقة الصناعية',
    postalCode: '81611',
    lat: 27.6831,
    lng: 41.5712,
    area: 25000,
    capacity: 100,
    status: SiteStatus.UNDER_PREPARATION,
    contactPerson: 'نايف القحطاني',
    contactPhone: '+201506641102',
    contactEmail: 'hal02@erp-construction.sa',
    description: 'مجمع صناعي لمعالجة المنتجات الغذائية الزراعية وتصنيعها وتعبئتها',
  },
  // الجوف (2 sites)
  {
    name: 'منطقة سكاكا الجوف الصناعية',
    code: 'SITE-JWF-001',
    city: 'سكاكا',
    state: 'منطقة الجوف',
    address: 'طريق الملك عبدالعزيز الصناعي حي العزيزية',
    postalCode: '72362',
    lat: 29.9731,
    lng: 40.2008,
    area: 500000,
    capacity: 100,
    status: SiteStatus.ACTIVE,
    contactPerson: 'محمد العتيبي',
    contactPhone: '+201504881101',
    contactEmail: 'jwf01@erp-construction.sa',
    description: 'تطوير مدينة سكاكا الصناعية ودعم مشاريع التعدين والطاقة المتجددة في الجوف',
  },
  {
    name: 'مشروع طريق الجوف الصحراوي الكبير',
    code: 'SITE-JWF-002',
    city: 'سكاكا',
    state: 'منطقة الجوف',
    address: 'طريق سكاكا دومة الجندل حي الصحراء',
    postalCode: '72311',
    lat: 29.7861,
    lng: 40.0993,
    area: 150000,
    capacity: 120,
    status: SiteStatus.UNDER_PREPARATION,
    contactPerson: 'خالد العنزي',
    contactPhone: '+201504881102',
    contactEmail: 'jwf02@erp-construction.sa',
    description: 'إنشاء طريق صحراوي جديد يربط منطقة الجوف بالمناطق السياحية والأثرية',
  },
];

export async function seedSites(prisma: PrismaClient, createdBy: string) {
  console.log('  Seeding Sites...');

  const createdSites: any[] = [];
  for (const def of siteDefs) {
    const site = await prisma.site.upsert({
      where: { code: def.code },
      update: {},
      create: {
        name: def.name,
        code: def.code,
        description: def.description,
        address: def.address,
        city: def.city,
        state: def.state,
        postalCode: def.postalCode,
        country: 'المملكة العربية السعودية',
        latitude: def.lat,
        longitude: def.lng,
        status: def.status,
        area: def.area,
        capacity: def.capacity,
        contactPerson: def.contactPerson,
        contactPhone: def.contactPhone,
        contactEmail: def.contactEmail,
        createdBy,
      },
    });
    createdSites.push(site);
  }

  console.log(` ${createdSites.length} Sites created`);
  return createdSites;
}
