/**
 * Employees Seed Data  LARGE DATASET
 * 60 employees: management, engineers, supervisors, technicians, workers
 */

import {
  PrismaClient,
  EmploymentType,
  EmployeeStatus,
  Gender,
} from '@prisma/client';

export async function seedEmployees(
  prisma: PrismaClient,
  createdBy: string,
  deptMap: Record<string, string> = {},
  posMap: Record<string, string> = {},
) {
  console.log(' Seeding Employees...');

  type EmpDef = {
    firstName: string;
    middleName: string;
    lastName: string;
    nationalId: string;
    employeeNumber: string;
    email: string;
    phone: string;
    dob: string;
    gender: Gender;
    nationality: string;
    address: string;
    city: string;
    state: string;
    postalCode: string;
    employmentType: EmploymentType;
    status: EmployeeStatus;
    department: string;
    position: string;
    hireDate: string;
    ecName: string;
    ecPhone: string;
    ecRel: string;
  };

  const defs: EmpDef[] = [
    //  الإدارة العليا (3)
    {
      firstName: 'عبدالعزيز',
      middleName: 'محمد',
      lastName: 'الشمري',
      nationalId: '1234567890',
      employeeNumber: 'EMP-2026-0001',
      email: 'a.alshammari@erp-construction.sa',
      phone: '+201509001001',
      dob: '1975-03-15',
      gender: Gender.MALE,
      nationality: 'Saudi',
      address: 'حي النخيل، شارع الأمير سلطان',
      city: 'الرياض',
      state: 'منطقة الرياض',
      postalCode: '11564',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Executive Management',
      position: 'General Manager',
      hireDate: '2018-01-01',
      ecName: 'نورة الشمري',
      ecPhone: '+201501234567',
      ecRel: 'زوجة',
    },
    {
      firstName: 'تركي',
      middleName: 'سالم',
      lastName: 'العصيمي',
      nationalId: '1234567891',
      employeeNumber: 'EMP-2026-0002',
      email: 't.alasimi@erp-construction.sa',
      phone: '+201509001002',
      dob: '1978-07-10',
      gender: Gender.MALE,
      nationality: 'Saudi',
      address: 'حي العليا، طريق الملك فهد',
      city: 'الرياض',
      state: 'منطقة الرياض',
      postalCode: '11564',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Operations',
      position: 'Chief Operations Officer',
      hireDate: '2018-03-01',
      ecName: 'سالم العصيمي',
      ecPhone: '+201502345678',
      ecRel: 'أب',
    },
    {
      firstName: 'فاطمة',
      middleName: 'أحمد',
      lastName: 'القحطاني',
      nationalId: '1234567892',
      employeeNumber: 'EMP-2026-0003',
      email: 'f.alqahtani@erp-construction.sa',
      phone: '+201509001003',
      dob: '1980-09-22',
      gender: Gender.FEMALE,
      nationality: 'Saudi',
      address: 'حي العليا، طريق الملك فهد',
      city: 'الرياض',
      state: 'منطقة الرياض',
      postalCode: '11564',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Finance',
      position: 'Chief Financial Officer',
      hireDate: '2019-01-15',
      ecName: 'أحمد القحطاني',
      ecPhone: '+201503456789',
      ecRel: 'أب',
    },
    //  الموارد البشرية والإدارة (5)
    {
      firstName: 'سارة',
      middleName: 'خالد',
      lastName: 'الزهراني',
      nationalId: '1234567893',
      employeeNumber: 'EMP-2026-0004',
      email: 's.alzahrani@erp-construction.sa',
      phone: '+201509001004',
      dob: '1988-04-15',
      gender: Gender.FEMALE,
      nationality: 'Saudi',
      address: 'حي الورود',
      city: 'الرياض',
      state: 'منطقة الرياض',
      postalCode: '11457',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Human Resources',
      position: 'HR Manager',
      hireDate: '2019-06-01',
      ecName: 'خالد الزهراني',
      ecPhone: '+201504567890',
      ecRel: 'أب',
    },
    {
      firstName: 'محمد',
      middleName: 'عبدالله',
      lastName: 'الحربي',
      nationalId: '1234567894',
      employeeNumber: 'EMP-2026-0005',
      email: 'm.alharbi@erp-construction.sa',
      phone: '+201509001005',
      dob: '1990-11-20',
      gender: Gender.MALE,
      nationality: 'Saudi',
      address: 'حي النزهة',
      city: 'جدة',
      state: 'منطقة مكة المكرمة',
      postalCode: '23324',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Human Resources',
      position: 'HR Specialist',
      hireDate: '2020-02-15',
      ecName: 'عبدالله الحربي',
      ecPhone: '+201505678901',
      ecRel: 'أب',
    },
    {
      firstName: 'منى',
      middleName: 'يوسف',
      lastName: 'الدوسري',
      nationalId: '1234567895',
      employeeNumber: 'EMP-2026-0006',
      email: 'm.aldossari@erp-construction.sa',
      phone: '+201509001006',
      dob: '1993-06-05',
      gender: Gender.FEMALE,
      nationality: 'Saudi',
      address: 'حي المروج',
      city: 'الرياض',
      state: 'منطقة الرياض',
      postalCode: '11451',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Human Resources',
      position: 'HR Coordinator',
      hireDate: '2021-09-01',
      ecName: 'يوسف الدوسري',
      ecPhone: '+201506789012',
      ecRel: 'أب',
    },
    {
      firstName: 'عمر',
      middleName: 'فهد',
      lastName: 'المطيري',
      nationalId: '1234567896',
      employeeNumber: 'EMP-2026-0007',
      email: 'o.almutairi@erp-construction.sa',
      phone: '+201509001007',
      dob: '1985-01-28',
      gender: Gender.MALE,
      nationality: 'Saudi',
      address: 'حي الخالدية',
      city: 'مكة المكرمة',
      state: 'منطقة مكة المكرمة',
      postalCode: '24231',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Administration',
      position: 'Office Manager',
      hireDate: '2019-11-10',
      ecName: 'فهد المطيري',
      ecPhone: '+201507890123',
      ecRel: 'أخ',
    },
    {
      firstName: 'نوف',
      middleName: 'سعد',
      lastName: 'الرشيد',
      nationalId: '1234567897',
      employeeNumber: 'EMP-2026-0008',
      email: 'n.alrashid@erp-construction.sa',
      phone: '+201509001008',
      dob: '1995-08-12',
      gender: Gender.FEMALE,
      nationality: 'Saudi',
      address: 'حي العقيق',
      city: 'الرياض',
      state: 'منطقة الرياض',
      postalCode: '12211',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Administration',
      position: 'Administrative Assistant',
      hireDate: '2022-03-01',
      ecName: 'سعد الرشيد',
      ecPhone: '+201508901234',
      ecRel: 'أب',
    },
    //  المهندسون (15)
    {
      firstName: 'خالد',
      middleName: 'عبدالله',
      lastName: 'الغامدي',
      nationalId: '1234567898',
      employeeNumber: 'EMP-2026-0009',
      email: 'k.alghamdi@erp-construction.sa',
      phone: '+201509001009',
      dob: '1987-11-10',
      gender: Gender.MALE,
      nationality: 'Saudi',
      address: 'حي الروضة',
      city: 'جدة',
      state: 'منطقة مكة المكرمة',
      postalCode: '23212',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Engineering',
      position: 'Senior Civil Engineer',
      hireDate: '2019-05-01',
      ecName: 'عبدالله الغامدي',
      ecPhone: '+201509012345',
      ecRel: 'أب',
    },
    {
      firstName: 'أحمد',
      middleName: 'سعد',
      lastName: 'العتيبي',
      nationalId: '1234567899',
      employeeNumber: 'EMP-2026-0010',
      email: 'a.alotaibi@erp-construction.sa',
      phone: '+201509001010',
      dob: '1989-04-18',
      gender: Gender.MALE,
      nationality: 'Saudi',
      address: 'حي الفيصلية',
      city: 'الدمام',
      state: 'المنطقة الشرقية',
      postalCode: '32241',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Engineering',
      position: 'Structural Engineer',
      hireDate: '2020-07-01',
      ecName: 'سعد العتيبي',
      ecPhone: '+201500123456',
      ecRel: 'أخ',
    },
    {
      firstName: 'مريم',
      middleName: 'يوسف',
      lastName: 'السبيعي',
      nationalId: '1234567900',
      employeeNumber: 'EMP-2026-0011',
      email: 'm.alsobihi@erp-construction.sa',
      phone: '+201509001011',
      dob: '1991-09-25',
      gender: Gender.FEMALE,
      nationality: 'Saudi',
      address: 'حي النهضة',
      city: 'الرياض',
      state: 'منطقة الرياض',
      postalCode: '11451',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Engineering',
      position: 'Electrical Engineer',
      hireDate: '2021-01-15',
      ecName: 'يوسف السبيعي',
      ecPhone: '+201501234568',
      ecRel: 'أب',
    },
    {
      firstName: 'عبدالرحمن',
      middleName: 'ناصر',
      lastName: 'الشهراني',
      nationalId: '1234567901',
      employeeNumber: 'EMP-2026-0012',
      email: 'ar.alshahrani@erp-construction.sa',
      phone: '+201509001012',
      dob: '1986-02-14',
      gender: Gender.MALE,
      nationality: 'Saudi',
      address: 'حي الشفاء',
      city: 'الرياض',
      state: 'منطقة الرياض',
      postalCode: '14253',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Engineering',
      position: 'Mechanical Engineer',
      hireDate: '2018-09-01',
      ecName: 'ناصر الشهراني',
      ecPhone: '+201502345679',
      ecRel: 'أب',
    },
    {
      firstName: 'مصطفى',
      middleName: 'أمين',
      lastName: 'إبراهيم',
      nationalId: '1234567902',
      employeeNumber: 'EMP-2026-0013',
      email: 'm.ibrahim@erp-construction.sa',
      phone: '+201509001013',
      dob: '1988-07-30',
      gender: Gender.MALE,
      nationality: 'Egyptian',
      address: 'حي العليا',
      city: 'الرياض',
      state: 'منطقة الرياض',
      postalCode: '11561',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Engineering',
      position: 'Civil Engineer',
      hireDate: '2020-03-01',
      ecName: 'أمين إبراهيم',
      ecPhone: '+201503456780',
      ecRel: 'أب',
    },
    {
      firstName: 'محمود',
      middleName: 'حسن',
      lastName: 'العزب',
      nationalId: '1234567903',
      employeeNumber: 'EMP-2026-0014',
      email: 'm.alazab@erp-construction.sa',
      phone: '+201509001014',
      dob: '1990-12-03',
      gender: Gender.MALE,
      nationality: 'Egyptian',
      address: 'حي المروج',
      city: 'جدة',
      state: 'منطقة مكة المكرمة',
      postalCode: '23232',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Engineering',
      position: 'Geotechnical Engineer',
      hireDate: '2021-06-01',
      ecName: 'حسن العزب',
      ecPhone: '+201504567891',
      ecRel: 'أب',
    },
    {
      firstName: 'أنس',
      middleName: 'محمد',
      lastName: 'الحامد',
      nationalId: '1234567904',
      employeeNumber: 'EMP-2026-0015',
      email: 'a.alhamid@erp-construction.sa',
      phone: '+201509001015',
      dob: '1992-05-17',
      gender: Gender.MALE,
      nationality: 'Jordanian',
      address: 'حي الصفاء',
      city: 'جدة',
      state: 'منطقة مكة المكرمة',
      postalCode: '23441',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Engineering',
      position: 'Architectural Engineer',
      hireDate: '2021-08-15',
      ecName: 'محمد الحامد',
      ecPhone: '+201505678902',
      ecRel: 'أب',
    },
    {
      firstName: 'ريان',
      middleName: 'فارس',
      lastName: 'العنزي',
      nationalId: '1234567905',
      employeeNumber: 'EMP-2026-0016',
      email: 'r.alanazi@erp-construction.sa',
      phone: '+201509001016',
      dob: '1989-08-22',
      gender: Gender.MALE,
      nationality: 'Saudi',
      address: 'حي العزيزية',
      city: 'الدمام',
      state: 'المنطقة الشرقية',
      postalCode: '32451',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Engineering',
      position: 'Electrical Engineer',
      hireDate: '2019-11-01',
      ecName: 'فارس العنزي',
      ecPhone: '+201506789013',
      ecRel: 'أب',
    },
    {
      firstName: 'هشام',
      middleName: 'علي',
      lastName: 'الأحمري',
      nationalId: '1234567906',
      employeeNumber: 'EMP-2026-0017',
      email: 'h.alahmari@erp-construction.sa',
      phone: '+201509001017',
      dob: '1984-03-11',
      gender: Gender.MALE,
      nationality: 'Saudi',
      address: 'حي السامر',
      city: 'أبها',
      state: 'منطقة عسير',
      postalCode: '62521',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Engineering',
      position: 'Senior Structural Engineer',
      hireDate: '2017-06-01',
      ecName: 'علي الأحمري',
      ecPhone: '+201507890124',
      ecRel: 'أب',
    },
    {
      firstName: 'ناصر',
      middleName: 'سليم',
      lastName: 'الوهيبي',
      nationalId: '1234567907',
      employeeNumber: 'EMP-2026-0018',
      email: 'n.alohaibi@erp-construction.sa',
      phone: '+201509001018',
      dob: '1991-10-07',
      gender: Gender.MALE,
      nationality: 'Saudi',
      address: 'حي الملز',
      city: 'الرياض',
      state: 'منطقة الرياض',
      postalCode: '11176',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Engineering',
      position: 'Project Engineer',
      hireDate: '2022-01-10',
      ecName: 'سليم الوهيبي',
      ecPhone: '+201508901235',
      ecRel: 'أب',
    },
    {
      firstName: 'كمال',
      middleName: 'جمال',
      lastName: 'عبدالسلام',
      nationalId: '1234567908',
      employeeNumber: 'EMP-2026-0019',
      email: 'k.abdelsalam@erp-construction.sa',
      phone: '+201509001019',
      dob: '1987-06-19',
      gender: Gender.MALE,
      nationality: 'Egyptian',
      address: 'حي النخيل',
      city: 'الرياض',
      state: 'منطقة الرياض',
      postalCode: '11564',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Engineering',
      position: 'MEP Coordinator',
      hireDate: '2020-09-01',
      ecName: 'جمال عبدالسلام',
      ecPhone: '+201509012346',
      ecRel: 'أب',
    },
    {
      firstName: 'دانة',
      middleName: 'عبدالعزيز',
      lastName: 'الفيصل',
      nationalId: '1234567909',
      employeeNumber: 'EMP-2026-0020',
      email: 'd.alfaisal@erp-construction.sa',
      phone: '+201509001020',
      dob: '1993-01-14',
      gender: Gender.FEMALE,
      nationality: 'Saudi',
      address: 'حي الياسمين',
      city: 'الرياض',
      state: 'منطقة الرياض',
      postalCode: '13326',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Engineering',
      position: 'Civil Engineer',
      hireDate: '2022-04-01',
      ecName: 'عبدالعزيز الفيصل',
      ecPhone: '+201500123457',
      ecRel: 'أب',
    },
    {
      firstName: 'بلال',
      middleName: 'صالح',
      lastName: 'الشريف',
      nationalId: '1234567910',
      employeeNumber: 'EMP-2026-0021',
      email: 'b.alsharif@erp-construction.sa',
      phone: '+201509001021',
      dob: '1986-09-28',
      gender: Gender.MALE,
      nationality: 'Jordanian',
      address: 'حي الروضة',
      city: 'الدمام',
      state: 'المنطقة الشرقية',
      postalCode: '32225',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Engineering',
      position: 'Environmental Engineer',
      hireDate: '2019-03-15',
      ecName: 'صالح الشريف',
      ecPhone: '+201501234569',
      ecRel: 'أب',
    },
    {
      firstName: 'رنا',
      middleName: 'سعيد',
      lastName: 'العمري',
      nationalId: '1234567911',
      employeeNumber: 'EMP-2026-0022',
      email: 'r.alamri@erp-construction.sa',
      phone: '+201509001022',
      dob: '1994-04-21',
      gender: Gender.FEMALE,
      nationality: 'Saudi',
      address: 'حي الندى',
      city: 'الرياض',
      state: 'منطقة الرياض',
      postalCode: '12211',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Engineering',
      position: 'Interior Design Engineer',
      hireDate: '2022-09-01',
      ecName: 'سعيد العمري',
      ecPhone: '+201502345680',
      ecRel: 'أب',
    },
    //  المشرفون (12)
    {
      firstName: 'سعد',
      middleName: 'فهد',
      lastName: 'المطيري',
      nationalId: '1234567912',
      employeeNumber: 'EMP-2026-0023',
      email: 's.almutairi@erp-construction.sa',
      phone: '+201509001023',
      dob: '1983-12-08',
      gender: Gender.MALE,
      nationality: 'Saudi',
      address: 'حي الخالدية',
      city: 'مكة المكرمة',
      state: 'منطقة مكة المكرمة',
      postalCode: '24231',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Operations',
      position: 'Senior Site Supervisor',
      hireDate: '2016-05-10',
      ecName: 'فهد المطيري',
      ecPhone: '+201503456781',
      ecRel: 'أخ',
    },
    {
      firstName: 'عبدالله',
      middleName: 'راشد',
      lastName: 'الشهري',
      nationalId: '1234567913',
      employeeNumber: 'EMP-2026-0024',
      email: 'a.alshahri@erp-construction.sa',
      phone: '+201509001024',
      dob: '1986-06-14',
      gender: Gender.MALE,
      nationality: 'Saudi',
      address: 'حي السامر',
      city: 'أبها',
      state: 'منطقة عسير',
      postalCode: '62521',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Operations',
      position: 'Safety Supervisor',
      hireDate: '2018-08-20',
      ecName: 'راشد الشهري',
      ecPhone: '+201504567892',
      ecRel: 'أب',
    },
    {
      firstName: 'إبراهيم',
      middleName: 'خليل',
      lastName: 'العوفي',
      nationalId: '1234567914',
      employeeNumber: 'EMP-2026-0025',
      email: 'i.alawfi@erp-construction.sa',
      phone: '+201509001025',
      dob: '1985-09-03',
      gender: Gender.MALE,
      nationality: 'Saudi',
      address: 'حي الروابي',
      city: 'الرياض',
      state: 'منطقة الرياض',
      postalCode: '14451',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Operations',
      position: 'Site Supervisor',
      hireDate: '2017-02-15',
      ecName: 'خليل العوفي',
      ecPhone: '+201505678903',
      ecRel: 'أب',
    },
    {
      firstName: 'منصور',
      middleName: 'طلال',
      lastName: 'الرويلي',
      nationalId: '1234567915',
      employeeNumber: 'EMP-2026-0026',
      email: 'm.alrouili@erp-construction.sa',
      phone: '+201509001026',
      dob: '1982-04-27',
      gender: Gender.MALE,
      nationality: 'Saudi',
      address: 'حي الفيصلية',
      city: 'تبوك',
      state: 'منطقة تبوك',
      postalCode: '71411',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Operations',
      position: 'Construction Supervisor',
      hireDate: '2015-10-01',
      ecName: 'طلال الرويلي',
      ecPhone: '+201506789014',
      ecRel: 'أب',
    },
    {
      firstName: 'ماجد',
      middleName: 'حمد',
      lastName: 'الحسيني',
      nationalId: '1234567916',
      employeeNumber: 'EMP-2026-0027',
      email: 'm.alhusaini@erp-construction.sa',
      phone: '+201509001027',
      dob: '1984-11-18',
      gender: Gender.MALE,
      nationality: 'Saudi',
      address: 'حي الصفاء',
      city: 'الدمام',
      state: 'المنطقة الشرقية',
      postalCode: '32254',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Quality',
      position: 'QA/QC Supervisor',
      hireDate: '2016-07-01',
      ecName: 'حمد الحسيني',
      ecPhone: '+201507890125',
      ecRel: 'أب',
    },
    {
      firstName: 'نادر',
      middleName: 'محمد',
      lastName: 'سليمان',
      nationalId: '1234567917',
      employeeNumber: 'EMP-2026-0028',
      email: 'n.suliman@erp-construction.sa',
      phone: '+201509001028',
      dob: '1981-03-22',
      gender: Gender.MALE,
      nationality: 'Egyptian',
      address: 'حي النسيم',
      city: 'جدة',
      state: 'منطقة مكة المكرمة',
      postalCode: '23458',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Operations',
      position: 'Site Supervisor',
      hireDate: '2014-01-15',
      ecName: 'محمد سليمان',
      ecPhone: '+201508901236',
      ecRel: 'أب',
    },
    {
      firstName: 'وائل',
      middleName: 'كمال',
      lastName: 'درويش',
      nationalId: '1234567918',
      employeeNumber: 'EMP-2026-0029',
      email: 'w.derwish@erp-construction.sa',
      phone: '+201509001029',
      dob: '1983-07-05',
      gender: Gender.MALE,
      nationality: 'Jordanian',
      address: 'حي الزهراء',
      city: 'الرياض',
      state: 'منطقة الرياض',
      postalCode: '11451',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Safety',
      position: 'HSE Supervisor',
      hireDate: '2016-11-10',
      ecName: 'كمال درويش',
      ecPhone: '+201509012347',
      ecRel: 'أب',
    },
    {
      firstName: 'فواز',
      middleName: 'عيد',
      lastName: 'العتيبي',
      nationalId: '1234567919',
      employeeNumber: 'EMP-2026-0030',
      email: 'f.alotaibi2@erp-construction.sa',
      phone: '+201509001030',
      dob: '1988-02-14',
      gender: Gender.MALE,
      nationality: 'Saudi',
      address: 'حي الفيصلية',
      city: 'بريدة',
      state: 'منطقة القصيم',
      postalCode: '52382',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Operations',
      position: 'Finishing Supervisor',
      hireDate: '2019-05-01',
      ecName: 'عيد العتيبي',
      ecPhone: '+201500123458',
      ecRel: 'أب',
    },
    {
      firstName: 'صالح',
      middleName: 'محمد',
      lastName: 'البقمي',
      nationalId: '1234567920',
      employeeNumber: 'EMP-2026-0031',
      email: 's.albaqmi@erp-construction.sa',
      phone: '+201509001031',
      dob: '1986-10-09',
      gender: Gender.MALE,
      nationality: 'Saudi',
      address: 'حي الخزامى',
      city: 'الرياض',
      state: 'منطقة الرياض',
      postalCode: '12241',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Operations',
      position: 'Concrete Works Supervisor',
      hireDate: '2018-01-20',
      ecName: 'محمد البقمي',
      ecPhone: '+201501234570',
      ecRel: 'أب',
    },
    {
      firstName: 'حاتم',
      middleName: 'صبري',
      lastName: 'أبو زيد',
      nationalId: '1234567921',
      employeeNumber: 'EMP-2026-0032',
      email: 'h.abuzaid@erp-construction.sa',
      phone: '+201509001032',
      dob: '1979-05-30',
      gender: Gender.MALE,
      nationality: 'Egyptian',
      address: 'حي المعيزيلة',
      city: 'الرياض',
      state: 'منطقة الرياض',
      postalCode: '11241',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Operations',
      position: 'Senior Supervisor',
      hireDate: '2013-08-01',
      ecName: 'صبري أبو زيد',
      ecPhone: '+201502345681',
      ecRel: 'أب',
    },
    {
      firstName: 'محمد',
      middleName: 'أسامة',
      lastName: 'البلوشي',
      nationalId: '1234567922',
      employeeNumber: 'EMP-2026-0033',
      email: 'm.albalushi@erp-construction.sa',
      phone: '+201509001033',
      dob: '1984-08-16',
      gender: Gender.MALE,
      nationality: 'Pakistani',
      address: 'حي الروضة',
      city: 'الدمام',
      state: 'المنطقة الشرقية',
      postalCode: '32225',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Operations',
      position: 'MEP Supervisor',
      hireDate: '2017-04-15',
      ecName: 'أسامة البلوشي',
      ecPhone: '+201503456782',
      ecRel: 'أب',
    },
    {
      firstName: 'خضر',
      middleName: 'حنا',
      lastName: 'جرجس',
      nationalId: '1234567923',
      employeeNumber: 'EMP-2026-0034',
      email: 'k.girgis@erp-construction.sa',
      phone: '+201509001034',
      dob: '1981-12-25',
      gender: Gender.MALE,
      nationality: 'Egyptian',
      address: 'حي الحمراء',
      city: 'جدة',
      state: 'منطقة مكة المكرمة',
      postalCode: '23241',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Quality',
      position: 'Quality Supervisor',
      hireDate: '2015-06-10',
      ecName: 'حنا جرجس',
      ecPhone: '+201504567893',
      ecRel: 'أب',
    },
    //  الفنيون (12)
    {
      firstName: 'حسن',
      middleName: 'علي',
      lastName: 'الزهراني',
      nationalId: '1234567924',
      employeeNumber: 'EMP-2026-0035',
      email: 'h.alzahrani@erp-construction.sa',
      phone: '+201509001035',
      dob: '1991-02-28',
      gender: Gender.MALE,
      nationality: 'Saudi',
      address: 'حي النسيم',
      city: 'الخبر',
      state: 'المنطقة الشرقية',
      postalCode: '34446',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Maintenance',
      position: 'Electrical Technician',
      hireDate: '2020-11-05',
      ecName: 'علي الزهراني',
      ecPhone: '+201505678904',
      ecRel: 'أب',
    },
    {
      firstName: 'محمد',
      middleName: 'سليمان',
      lastName: 'البلوي',
      nationalId: '1234567925',
      employeeNumber: 'EMP-2026-0036',
      email: 'm.albalawi@erp-construction.sa',
      phone: '+201509001036',
      dob: '1993-08-16',
      gender: Gender.MALE,
      nationality: 'Saudi',
      address: 'حي المروة',
      city: 'تبوك',
      state: 'منطقة تبوك',
      postalCode: '71491',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Maintenance',
      position: 'HVAC Technician',
      hireDate: '2021-07-12',
      ecName: 'سليمان البلوي',
      ecPhone: '+201506789015',
      ecRel: 'أب',
    },
    {
      firstName: 'رامز',
      middleName: 'فيصل',
      lastName: 'الوادي',
      nationalId: '1234567926',
      employeeNumber: 'EMP-2026-0037',
      email: 'r.alwadi@erp-construction.sa',
      phone: '+201509001037',
      dob: '1989-05-11',
      gender: Gender.MALE,
      nationality: 'Yemeni',
      address: 'حي الصفاء',
      city: 'جدة',
      state: 'منطقة مكة المكرمة',
      postalCode: '23452',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Maintenance',
      position: 'Plumbing Technician',
      hireDate: '2019-03-01',
      ecName: 'فيصل الوادي',
      ecPhone: '+201507890126',
      ecRel: 'أب',
    },
    {
      firstName: 'سيد',
      middleName: 'ممدوح',
      lastName: 'عوض',
      nationalId: '1234567927',
      employeeNumber: 'EMP-2026-0038',
      email: 's.awad@erp-construction.sa',
      phone: '+201509001038',
      dob: '1987-10-19',
      gender: Gender.MALE,
      nationality: 'Egyptian',
      address: 'حي الروابي',
      city: 'الرياض',
      state: 'منطقة الرياض',
      postalCode: '14451',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Maintenance',
      position: 'Electrical Technician',
      hireDate: '2020-01-20',
      ecName: 'ممدوح عوض',
      ecPhone: '+201508901237',
      ecRel: 'أب',
    },
    {
      firstName: 'علي',
      middleName: 'جاسم',
      lastName: 'الأمين',
      nationalId: '1234567928',
      employeeNumber: 'EMP-2026-0039',
      email: 'a.alamin@erp-construction.sa',
      phone: '+201509001039',
      dob: '1992-03-07',
      gender: Gender.MALE,
      nationality: 'Pakistani',
      address: 'حي الخبر الجنوبي',
      city: 'الخبر',
      state: 'المنطقة الشرقية',
      postalCode: '34441',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Maintenance',
      position: 'HVAC Technician',
      hireDate: '2021-05-01',
      ecName: 'جاسم الأمين',
      ecPhone: '+201509012348',
      ecRel: 'أخ',
    },
    {
      firstName: 'ياسر',
      middleName: 'طارق',
      lastName: 'العيسى',
      nationalId: '1234567929',
      employeeNumber: 'EMP-2026-0040',
      email: 'y.aleisa@erp-construction.sa',
      phone: '+201509001040',
      dob: '1990-07-23',
      gender: Gender.MALE,
      nationality: 'Saudi',
      address: 'حي الشرفية',
      city: 'جدة',
      state: 'منطقة مكة المكرمة',
      postalCode: '23241',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Maintenance',
      position: 'Welding Technician',
      hireDate: '2020-08-15',
      ecName: 'طارق العيسى',
      ecPhone: '+201500123459',
      ecRel: 'أب',
    },
    {
      firstName: 'حمزة',
      middleName: 'جواد',
      lastName: 'اليمني',
      nationalId: '1234567930',
      employeeNumber: 'EMP-2026-0041',
      email: 'h.alyamani@erp-construction.sa',
      phone: '+201509001041',
      dob: '1988-11-14',
      gender: Gender.MALE,
      nationality: 'Yemeni',
      address: 'حي القدس',
      city: 'الرياض',
      state: 'منطقة الرياض',
      postalCode: '11457',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Maintenance',
      position: 'Plumbing Technician',
      hireDate: '2019-09-01',
      ecName: 'جواد اليمني',
      ecPhone: '+201501234571',
      ecRel: 'أب',
    },
    {
      firstName: 'راجيف',
      middleName: 'كومار',
      lastName: 'شارما',
      nationalId: '1234567931',
      employeeNumber: 'EMP-2026-0042',
      email: 'r.sharma@erp-construction.sa',
      phone: '+201509001042',
      dob: '1985-06-08',
      gender: Gender.MALE,
      nationality: 'Indian',
      address: 'حي النهضة',
      city: 'الدمام',
      state: 'المنطقة الشرقية',
      postalCode: '32241',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Maintenance',
      position: 'Electrical Technician',
      hireDate: '2018-02-01',
      ecName: 'سيما شارما',
      ecPhone: '+201502345682',
      ecRel: 'زوجة',
    },
    {
      firstName: 'عمر',
      middleName: 'بكر',
      lastName: 'الحسن',
      nationalId: '1234567932',
      employeeNumber: 'EMP-2026-0043',
      email: 'o.alhassan@erp-construction.sa',
      phone: '+201509001043',
      dob: '1994-02-18',
      gender: Gender.MALE,
      nationality: 'Saudi',
      address: 'حي الواحة',
      city: 'الرياض',
      state: 'منطقة الرياض',
      postalCode: '11452',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Maintenance',
      position: 'Fire Systems Technician',
      hireDate: '2022-06-01',
      ecName: 'بكر الحسن',
      ecPhone: '+201503456783',
      ecRel: 'أب',
    },
    {
      firstName: 'صلاح',
      middleName: 'سامي',
      lastName: 'قنديل',
      nationalId: '1234567933',
      employeeNumber: 'EMP-2026-0044',
      email: 's.kandeel@erp-construction.sa',
      phone: '+201509001044',
      dob: '1986-12-01',
      gender: Gender.MALE,
      nationality: 'Egyptian',
      address: 'حي الصواري',
      city: 'جدة',
      state: 'منطقة مكة المكرمة',
      postalCode: '23411',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Maintenance',
      position: 'HVAC Technician',
      hireDate: '2018-07-15',
      ecName: 'سامي قنديل',
      ecPhone: '+201504567894',
      ecRel: 'أب',
    },
    {
      firstName: 'فريد',
      middleName: 'حسين',
      lastName: 'الرحيمي',
      nationalId: '1234567934',
      employeeNumber: 'EMP-2026-0045',
      email: 'f.alrahimi@erp-construction.sa',
      phone: '+201509001045',
      dob: '1990-04-12',
      gender: Gender.MALE,
      nationality: 'Pakistani',
      address: 'حي النزهة',
      city: 'الرياض',
      state: 'منطقة الرياض',
      postalCode: '12244',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Maintenance',
      position: 'Instrumentation Technician',
      hireDate: '2020-10-01',
      ecName: 'حسين الرحيمي',
      ecPhone: '+201505678905',
      ecRel: 'أب',
    },
    {
      firstName: 'فرحان',
      middleName: 'احمد',
      lastName: 'نصر',
      nationalId: '1234567935',
      employeeNumber: 'EMP-2026-0046',
      email: 'f.nasr@erp-construction.sa',
      phone: '+201509001046',
      dob: '1988-08-25',
      gender: Gender.MALE,
      nationality: 'Egyptian',
      address: 'حي الروضة',
      city: 'الأحساء',
      state: 'المنطقة الشرقية',
      postalCode: '31982',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Maintenance',
      position: 'Welding Technician',
      hireDate: '2019-12-01',
      ecName: 'أحمد نصر',
      ecPhone: '+201506789016',
      ecRel: 'أب',
    },
    //  العمال والمشغلون (8)
    {
      firstName: 'يوسف',
      middleName: 'حسين',
      lastName: 'العجمي',
      nationalId: '1234567936',
      employeeNumber: 'EMP-2026-0047',
      email: 'y.alajmi@erp-construction.sa',
      phone: '+201509001047',
      dob: '1984-10-30',
      gender: Gender.MALE,
      nationality: 'Saudi',
      address: 'حي الفردوس',
      city: 'جدة',
      state: 'منطقة مكة المكرمة',
      postalCode: '23212',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Operations',
      position: 'Heavy Equipment Operator',
      hireDate: '2017-03-22',
      ecName: 'حسين العجمي',
      ecPhone: '+201507890127',
      ecRel: 'أب',
    },
    {
      firstName: 'طارق',
      middleName: 'المهدي',
      lastName: 'بشير',
      nationalId: '1234567937',
      employeeNumber: 'EMP-2026-0048',
      email: 't.beshir@erp-construction.sa',
      phone: '+201509001048',
      dob: '1985-01-22',
      gender: Gender.MALE,
      nationality: 'Egyptian',
      address: 'حي الروضة',
      city: 'الرياض',
      state: 'منطقة الرياض',
      postalCode: '12245',
      employmentType: EmploymentType.CONTRACT,
      status: EmployeeStatus.ACTIVE,
      department: 'Operations',
      position: 'Crane Operator',
      hireDate: '2022-01-01',
      ecName: 'المهدي بشير',
      ecPhone: '+201508901238',
      ecRel: 'أب',
    },
    {
      firstName: 'سانتوش',
      middleName: 'كومار',
      lastName: 'باتيل',
      nationalId: '1234567938',
      employeeNumber: 'EMP-2026-0049',
      email: 's.patel@erp-construction.sa',
      phone: '+201509001049',
      dob: '1987-05-17',
      gender: Gender.MALE,
      nationality: 'Indian',
      address: 'حي الفيصلية',
      city: 'الدمام',
      state: 'المنطقة الشرقية',
      postalCode: '32241',
      employmentType: EmploymentType.CONTRACT,
      status: EmployeeStatus.ACTIVE,
      department: 'Operations',
      position: 'Excavator Operator',
      hireDate: '2021-09-01',
      ecName: 'ليلا باتيل',
      ecPhone: '+201509012349',
      ecRel: 'زوجة',
    },
    {
      firstName: 'عادل',
      middleName: 'رشاد',
      lastName: 'عبدالرحمن',
      nationalId: '1234567939',
      employeeNumber: 'EMP-2026-0050',
      email: 'a.abdulrahman@erp-construction.sa',
      phone: '+201509001050',
      dob: '1983-09-08',
      gender: Gender.MALE,
      nationality: 'Egyptian',
      address: 'حي السامر',
      city: 'جدة',
      state: 'منطقة مكة المكرمة',
      postalCode: '23454',
      employmentType: EmploymentType.CONTRACT,
      status: EmployeeStatus.ACTIVE,
      department: 'Operations',
      position: 'Carpenter',
      hireDate: '2021-04-10',
      ecName: 'رشاد عبدالرحمن',
      ecPhone: '+201500123460',
      ecRel: 'أب',
    },
    {
      firstName: 'نواف',
      middleName: 'محمد',
      lastName: 'السلمي',
      nationalId: '1234567940',
      employeeNumber: 'EMP-2026-0051',
      email: 'n.alsalmi@erp-construction.sa',
      phone: '+201509001051',
      dob: '1991-07-15',
      gender: Gender.MALE,
      nationality: 'Saudi',
      address: 'حي قبلة',
      city: 'المدينة المنورة',
      state: 'منطقة المدينة المنورة',
      postalCode: '42311',
      employmentType: EmploymentType.CONTRACT,
      status: EmployeeStatus.ACTIVE,
      department: 'Operations',
      position: 'Steel Fixing Worker',
      hireDate: '2022-11-01',
      ecName: 'محمد السلمي',
      ecPhone: '+201501234572',
      ecRel: 'أب',
    },
    {
      firstName: 'داود',
      middleName: 'إدريس',
      lastName: 'الخان',
      nationalId: '1234567941',
      employeeNumber: 'EMP-2026-0052',
      email: 'd.alkhan@erp-construction.sa',
      phone: '+201509001052',
      dob: '1988-03-26',
      gender: Gender.MALE,
      nationality: 'Pakistani',
      address: 'حي الشفاء',
      city: 'الرياض',
      state: 'منطقة الرياض',
      postalCode: '14253',
      employmentType: EmploymentType.CONTRACT,
      status: EmployeeStatus.ACTIVE,
      department: 'Operations',
      position: 'Masonry Worker',
      hireDate: '2021-08-15',
      ecName: 'إدريس الخان',
      ecPhone: '+201502345683',
      ecRel: 'أب',
    },
    {
      firstName: 'مختار',
      middleName: 'أمين',
      lastName: 'التيجاني',
      nationalId: '1234567942',
      employeeNumber: 'EMP-2026-0053',
      email: 'm.teejani@erp-construction.sa',
      phone: '+201509001053',
      dob: '1986-11-05',
      gender: Gender.MALE,
      nationality: 'Egyptian',
      address: 'حي النهضة',
      city: 'جدة',
      state: 'منطقة مكة المكرمة',
      postalCode: '23461',
      employmentType: EmploymentType.CONTRACT,
      status: EmployeeStatus.ACTIVE,
      department: 'Operations',
      position: 'Painting Worker',
      hireDate: '2022-03-10',
      ecName: 'أمين التيجاني',
      ecPhone: '+201503456784',
      ecRel: 'أب',
    },
    {
      firstName: 'عبدالنور',
      middleName: 'يوسف',
      lastName: 'الأمين',
      nationalId: '1234567943',
      employeeNumber: 'EMP-2026-0054',
      email: 'an.alamin@erp-construction.sa',
      phone: '+201509001054',
      dob: '1990-06-20',
      gender: Gender.MALE,
      nationality: 'Yemeni',
      address: 'حي الأمانة',
      city: 'الرياض',
      state: 'منطقة الرياض',
      postalCode: '11531',
      employmentType: EmploymentType.CONTRACT,
      status: EmployeeStatus.ACTIVE,
      department: 'Operations',
      position: 'Construction Worker',
      hireDate: '2022-07-01',
      ecName: 'يوسف الأمين',
      ecPhone: '+201504567895',
      ecRel: 'أب',
    },
    //  إضافيون (المحاسبة والمشتريات والإدارة) (6)
    {
      firstName: 'عبدالله',
      middleName: 'سعود',
      lastName: 'الحمدان',
      nationalId: '1234567944',
      employeeNumber: 'EMP-2026-0055',
      email: 'a.alhamdan@erp-construction.sa',
      phone: '+201509001055',
      dob: '1985-02-10',
      gender: Gender.MALE,
      nationality: 'Saudi',
      address: 'حي الربيع',
      city: 'الرياض',
      state: 'منطقة الرياض',
      postalCode: '14812',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Finance',
      position: 'Senior Accountant',
      hireDate: '2018-06-01',
      ecName: 'سعود الحمدان',
      ecPhone: '+201505678906',
      ecRel: 'أب',
    },
    {
      firstName: 'هيفاء',
      middleName: 'عبدالرحمن',
      lastName: 'الرفاعي',
      nationalId: '1234567945',
      employeeNumber: 'EMP-2026-0056',
      email: 'h.alrifai@erp-construction.sa',
      phone: '+201509001056',
      dob: '1992-10-28',
      gender: Gender.FEMALE,
      nationality: 'Saudi',
      address: 'حي الواحة',
      city: 'الرياض',
      state: 'منطقة الرياض',
      postalCode: '11452',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Finance',
      position: 'Accountant',
      hireDate: '2021-01-10',
      ecName: 'عبدالرحمن الرفاعي',
      ecPhone: '+201506789017',
      ecRel: 'أب',
    },
    {
      firstName: 'عيسى',
      middleName: 'عبدالله',
      lastName: 'المنصور',
      nationalId: '1234567946',
      employeeNumber: 'EMP-2026-0057',
      email: 'e.almansour@erp-construction.sa',
      phone: '+201509001057',
      dob: '1987-07-14',
      gender: Gender.MALE,
      nationality: 'Saudi',
      address: 'حي طيبة',
      city: 'المدينة المنورة',
      state: 'منطقة المدينة المنورة',
      postalCode: '42325',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Procurement',
      position: 'Procurement Manager',
      hireDate: '2019-04-01',
      ecName: 'عبدالله المنصور',
      ecPhone: '+201507890128',
      ecRel: 'أب',
    },
    {
      firstName: 'أسماء',
      middleName: 'حامد',
      lastName: 'العبدالكريم',
      nationalId: '1234567947',
      employeeNumber: 'EMP-2026-0058',
      email: 'a.alkarim@erp-construction.sa',
      phone: '+201509001058',
      dob: '1993-12-07',
      gender: Gender.FEMALE,
      nationality: 'Saudi',
      address: 'حي الروضة',
      city: 'جدة',
      state: 'منطقة مكة المكرمة',
      postalCode: '23452',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'Procurement',
      position: 'Procurement Specialist',
      hireDate: '2022-02-15',
      ecName: 'حامد العبدالكريم',
      ecPhone: '+201508901239',
      ecRel: 'أب',
    },
    {
      firstName: 'فهد',
      middleName: 'عبدالرحمن',
      lastName: 'الخليل',
      nationalId: '1234567948',
      employeeNumber: 'EMP-2026-0059',
      email: 'f.alkhalil@erp-construction.sa',
      phone: '+201509001059',
      dob: '1989-09-19',
      gender: Gender.MALE,
      nationality: 'Saudi',
      address: 'حي الشعلة',
      city: 'الدمام',
      state: 'المنطقة الشرقية',
      postalCode: '32241',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'IT',
      position: 'IT Manager',
      hireDate: '2020-05-01',
      ecName: 'عبدالرحمن الخليل',
      ecPhone: '+201509012350',
      ecRel: 'أب',
    },
    {
      firstName: 'لوسي',
      middleName: 'جوزيف',
      lastName: 'نصرالله',
      nationalId: '1234567949',
      employeeNumber: 'EMP-2026-0060',
      email: 'l.nasrallah@erp-construction.sa',
      phone: '+201509001060',
      dob: '1990-01-13',
      gender: Gender.FEMALE,
      nationality: 'Lebanese',
      address: 'حي النزهة',
      city: 'الرياض',
      state: 'منطقة الرياض',
      postalCode: '12244',
      employmentType: EmploymentType.PERMANENT,
      status: EmployeeStatus.ACTIVE,
      department: 'IT',
      position: 'Systems Analyst',
      hireDate: '2021-11-01',
      ecName: 'جوزيف نصرالله',
      ecPhone: '+201500123461',
      ecRel: 'أب',
    },
  ];

  const createdEmployees: any[] = [];
  for (const d of defs) {
    const emp = await prisma.employee.upsert({
      where: { nationalId: d.nationalId },
      update: {},
      create: {
        firstName: d.firstName,
        middleName: d.middleName,
        lastName: d.lastName,
        nationalId: d.nationalId,
        employeeNumber: d.employeeNumber,
        email: d.email,
        phone: d.phone,
        dateOfBirth: new Date(d.dob),
        gender: d.gender,
        nationality: d.nationality,
        address: d.address,
        city: d.city,
        state: d.state,
        postalCode: d.postalCode,
        country: 'السعودية',
        employmentType: d.employmentType,
        status: d.status,
        hireDate: new Date(d.hireDate),
        departmentId: deptMap[d.department] ?? null,
        positionId: posMap[d.position] ?? null,
        emergencyContactName: d.ecName,
        emergencyContactPhone: d.ecPhone,
        emergencyContactRelation: d.ecRel,
        createdBy,
      },
    });
    createdEmployees.push(emp);
  }

  console.log(` ${createdEmployees.length} Employees created`);
  return createdEmployees;
}

