/**
 * Employees Module - English Translations
 */

import {
  EmployeeStatus,
  EmploymentType,
  Gender,
} from "@/types/employees.types";

export const employeesEn = {
  title: "Employees",
  subtitle: "Manage Employee Data",

  list: {
    title: "Employees List",
    description: "View and manage all company employees",
    empty: "No employees found",
    emptyDescription: "Start by adding a new employee",
    loading: "Loading employees...",
    errorLoading: "Error loading employees list",
  },

  stats: {
    total: "Total Employees",
    active: "Active",
    inactive: "Inactive",
    onLeave: "On Leave",
    terminated: "Terminated",
  },

  table: {
    employeeNumber: "Employee #",
    photo: "Photo",
    fullName: "Full Name",
    nationalId: "National ID",
    phone: "Phone",
    email: "Email",
    department: "Department",
    position: "Position",
    employmentType: "Employment Type",
    status: "Status",
    hireDate: "Hire Date",
    actions: "Actions",
  },

  form: {
    createTitle: "Add New Employee",
    createDescription: "Add a new employee to the system",
    editTitle: "Edit Employee",
    editDescription: "Update employee information",
    employeeInfo: "Employee Information",
    editEmployeeInfo: "Edit Employee Information",

    tabs: {
      personal: "Personal Information",
      employment: "Employment Information",
      contact: "Contact Information",
      emergency: "Emergency Contact",
    },

    fields: {
      firstName: "First Name",
      lastName: "Last Name",
      middleName: "Middle Name",
      nationalId: "National ID Number",
      employeeNumber: "Employee Number",
      email: "Email Address",
      phone: "Phone Number",
      alternatePhone: "Alternate Phone",
      alternativePhone: "Alternative Phone",
      dateOfBirth: "Date of Birth",
      gender: "Gender",
      nationality: "Nationality",
      address: "Address",
      city: "City",
      state: "State/Province",
      postalCode: "Postal Code",
      country: "Country",
      employmentType: "Employment Type",
      status: "Status",
      department: "Department",
      position: "Position",
      hireDate: "Hire Date",
      rehireDate: "Rehire Date",
      terminationDate: "Termination Date",
      rehireReason: "Rehire Reason",
      terminationReason: "Termination Reason",
      emergencyContactName: "Emergency Contact Name",
      emergencyContactPhone: "Emergency Contact Phone",
      emergencyContactRelation: "Relationship",
      notes: "Notes",
      documents: "Documents",
    },

    descriptions: {
      nationalId: "Must be 10 digits and start with 1 (Saudi) or 2 (Resident)",
      employeeNumber: "Will be auto-generated if left empty",
      phone: "Optional. International format supported (e.g., +201234567890)",
      statusDefault: "New employees start with 'Active' status by default",
      emergencyContactRelation: "e.g., Father, Mother, Spouse, Sibling",
      notes: "Any additional information or special notes about the employee",
      documents:
        "Upload employee-related documents (photo, contract, certificates)",
    },

    fileUpload: {
      title: "Upload Documents",
      description:
        "You can upload employee documents such as photo, contract, certificates",
      maxSize: "Maximum size",
      acceptedTypes: "Accepted types",
      dragDrop: "Drag and drop files here",
      or: "or",
      browse: "Browse Files",
      uploadedFiles: "Uploaded Files",
      ready: "Ready to upload",
      errors: {
        fileSize: "File size exceeds 5MB",
        fileType: "Unsupported file type. Accepted: JPG, PNG, WebP, PDF",
      },
    },

    sections: {
      basicInfo: {
        title: "Employee Information",
        description:
          "Required fields to create an employee (name, ID, employment type, hire date)",
      },
      employmentInfo: {
        title: "Employment Details",
        description: "Optional - can be added later",
      },
      contactInfo: {
        title: "Contact Information",
        description: "Optional - email, phone, and address",
      },
      emergencyContact: {
        title: "Emergency Contact",
        description: "Optional - recommended for emergency situations",
      },
      additionalInfo: {
        title: "Additional Information",
        description: "Optional - notes or other details",
      },
    },

    autoGeneratedNumber: {
      title: "Auto-Generated Number",
      description:
        "Employee number will be generated automatically upon saving",
    },

    emergencyAlert: {
      title: "Important Information",
      description:
        "Please add at least one emergency contact. This information is crucial in case of emergencies.",
    },

    placeholders: {
      firstName: "Enter first name",
      lastName: "Enter last name",
      middleName: "Enter middle name (optional)",
      nationalId: "1234567890",
      employeeNumber: "EMP-001",
      email: "employee@company.com",
      phone: "+201234567890",
      alternatePhone: "+201234567891",
      alternativePhone: "+201234567891",
      dateOfBirth: "Select date of birth",
      gender: "Select gender",
      nationality: "Enter nationality",
      address: "Enter full address",
      city: "Enter city",
      state: "Enter state/province",
      postalCode: "12345",
      country: "المملكه العربيه السعوديه",
      employmentType: "Select employment type",
      status: "Select status",
      department: "Select or enter department",
      position: "Select or enter position",
      hireDate: "Select hire date",
      terminationDate: "Select termination date",
      terminationReason: "Enter termination reason",
      emergencyContactName: "Enter contact name",
      emergencyContactPhone: "+201234567890",
      emergencyContactRelation: "e.g., Father, Mother, Spouse",
      notes: "Enter any additional notes",
    },

    validation: {
      required: "This field is required",
      invalidEmail: "Invalid email address",
      invalidPhone: "Invalid phone number",
      invalidNationalId: "Invalid national ID (10 digits)",
      minLength: "Must be at least {{min}} characters",
      maxLength: "Must not exceed {{max}} characters",
      invalidDate: "Invalid date",
      hireDateFuture: "Hire date cannot be in the future",
      terminationBeforeHire: "Termination date cannot be before hire date",
      firstNameRequired: "First name is required",
      firstNameMax: "First name must not exceed 100 characters",
      lastNameRequired: "Last name is required",
      lastNameMax: "Last name must not exceed 100 characters",
      nationalIdRequired: "National ID is required",
      nationalIdInvalid:
        "National ID must be 10 digits and start with 1 (Saudi) or 2 (Resident)",
      genderRequired: "Gender is required",
      employmentTypeRequired: "Employment type is required",
      statusRequired: "Status is required",
      hireDateRequired: "Hire date is required",
      emailInvalid: "Invalid email address",
      phoneInvalid: "Invalid phone number (e.g., +201234567890)",
      terminationDateInvalid: "Termination date must be after hire date",
      terminationDateRequired:
        "Termination date is required when status is set to 'Terminated'",
    },
  },

  filters: {
    title: "Filters",
    search: "Search...",
    searchPlaceholder: "Search by name, phone, or ID...",
    employmentType: "Employment Type",
    status: "Status",
    department: "Department",
    position: "Position",
    nationality: "Nationality",
    country: "Country",
    reset: "Reset",
    apply: "Apply",
    allEmploymentTypes: "All Employment Types",
    allTypes: "All Types",
    allStatuses: "All Statuses",
    allDepartments: "All Departments",
    allPositions: "All Positions",
  },

  actions: {
    create: "Add Employee",
    edit: "Edit",
    delete: "Delete",
    view: "View Details",
    openMenu: "Open menu",
    bulkCreate: "Bulk Create",
    export: "Export",
    import: "Import",
    print: "Print",
  },

  status: {
    [EmployeeStatus.ACTIVE]: "Active",
    [EmployeeStatus.INACTIVE]: "Inactive",
    [EmployeeStatus.ON_LEAVE]: "On Leave",
    [EmployeeStatus.SUSPENDED]: "Suspended",
    [EmployeeStatus.TERMINATED]: "Terminated",
  },

  employmentType: {
    [EmploymentType.PERMANENT]: "Permanent",
    [EmploymentType.CONTRACT]: "Company Sponsorship",
    [EmploymentType.TEMPORARY]: "Temporary",
    [EmploymentType.PART_TIME]: "Part Time",
    [EmploymentType.FULL_TIME]: "Full Time",
    [EmploymentType.FREELANCE]: "External Labor",
    [EmploymentType.CONSULTANT]: "Consultant",
    [EmploymentType.INTERN]: "Intern",
    [EmploymentType.TRAINEE]: "Trainee",
    [EmploymentType.SEASONAL]: "Seasonal",
    [EmploymentType.ON_CALL]: "On-Call",
    [EmploymentType.PROBATION]: "Probation",
    [EmploymentType.REMOTE]: "Remote",
  },

  gender: {
    [Gender.MALE]: "Male",
    [Gender.FEMALE]: "Female",
    [Gender.OTHER]: "Other",
  },

  create: {
    success: "Employee added successfully",
    error: "Failed to add employee",
    nationalIdExists: "National ID is already registered in the system",
    employeeNumberExists: "Employee number already exists",
    emailExists: "Email is already registered for another employee",
    phoneExists: "Phone number is already registered for another employee",
  },

  bulkCreate: {
    success: "{{count}} employees added successfully",
    error: "Failed to bulk create employees",
    partial: "{{success}} of {{total}} employees added",
  },

  update: {
    success: "Employee updated successfully",
    error: "Failed to update employee",
  },

  delete: {
    success: "Employee deleted successfully",
    error: "Failed to delete employee",
    confirm: "Are you sure you want to delete this employee?",
    confirmTitle: "Confirm Deletion",
    confirmMessage:
      "{{name}} will be removed from the database. This action cannot be undone.",
  },

  tabs: {
    overview: "Overview",
    salary: "Salary",
    allowances: "Allowances",
    loans: "Loans",
    deductions: "Deductions",
    documents: "Documents",
  },

  details: {
    title: "Employee Details",
    personalInfo: "Personal Information",
    employmentInfo: "Employment Information",
    contactInfo: "Contact Information",
    emergencyContact: "Emergency Contact",
    employmentDuration: "Employment Duration",
    currentSalary: "Current Salary",
    noSalaryAssigned: "No salary assigned",
    joinedDate: "Joined Date",
    createdAt: "Created At",
    updatedAt: "Updated At",
    documents: "Documents",
  },

  // Documents Section
  documents: {
    title: "Documents",
    count: "document",
    empty: "No documents uploaded",
    emptyHint: "Start by uploading employee documents",
    type: "Type",
    name: "Name",
    issueDate: "Issue Date",
    expiryDate: "Expiry Date",
    status: "Status",
    notes: "Notes",
    filesSelected: "file selected",
    namePlaceholder: "e.g., Employment Contract 2026",
    notesPlaceholder: "Additional notes...",

    types: {
      ID_CARD: "ID Card",
      PASSPORT: "Passport",
      CONTRACT: "Employment Contract",
      CERTIFICATE: "Certificate",
      OTHER: "Other",
    },

    statusLabels: {
      valid: "Valid",
      expiring: "Expiring in {{days}} days",
      expired: "Expired",
      noExpiry: "No Expiry",
    },

    validation: {
      issueDateFuture: "Issue date cannot be in the future",
      expiryNeedsIssue: "Issue date must be set first",
      expiryBeforeIssue: "Expiry date must be after issue date",
    },

    upload: {
      success: "Documents uploaded successfully",
      error: "Failed to upload documents",
    },

    delete: {
      success: "Document deleted successfully",
      error: "Failed to delete document",
    },
  },

  profilePicture: {
    upload: {
      success: "Profile picture uploaded successfully",
      error: "Failed to upload profile picture",
    },
    delete: {
      success: "Profile picture deleted successfully",
      error: "Failed to delete profile picture",
    },
  },

  helpSteps: {
    title: "Help Steps",
    list: {
      step1: "Use filters to search for specific employees",
      step2: "Click on employee name to view details",
      step3: "You can edit or delete employees from the actions menu",
      step4: "Use 'Add Employee' button to add a new employee",
      step5: "You can export the list to Excel",
    },
    create: {
      step1:
        "Fill required fields in Step 1 (Name, National ID, Employment Type, Hire Date) - You can save immediately!",
      step2:
        "Use 'Next' to move to other steps, or click 'Save' directly from Step 1",
      step3:
        "You can add remaining info (Employment, Contact, Emergency) anytime - all optional",
      step4: "Click any step in the top bar to jump directly to it",
      step5:
        "If a red badge appears on a step, click it to see and fix the error",
    },
    edit: {
      step1: "Use steps to navigate between different data sections",
      step2: "Edit any field in any step - data is preserved during navigation",
      step3: "Upload new documents or remove old ones in the Documents step",
      step4: "Click 'Save' from any step to apply all modifications",
    },
    step1:
      "Step 1: Start by entering basic personal information (name, ID, phone)",
    step2:
      "Step 2: Enter employment information (type, department, position, hire date)",
    step3: "Step 3: Fill in contact and address details",
    step4: "Step 4: Add emergency contact information (important)",
    step5: "Step 5: Review all data and click Save",
  },

  messages: {
    noResults: "No results found",
    loadingError: "An error occurred while loading data",
    retry: "Retry",
    statusUpdated: "Employee status updated successfully",
  },

  quickActions: {
    title: "Quick Actions",
    changeStatus: {
      button: "Change Status",
      title: "Change Employee Status",
      description: "Quickly change employee status without full edit",
      currentStatus: "Current Status",
      newStatus: "New Status",
    },
    viewDocuments: "View Documents",
    viewDocumentsDesc: "View and manage employee documents",
    changeDepartment: "Change Department",
    changeDepartmentDesc: "Change employee's department",
    currentDepartment: "Current Department",
    newDepartment: "New Department",
    noDepartment: "No Department",
    changeDepartmentFor: "Change Department: {{name}}",
    changePosition: "Change Position",
    changePositionDesc: "Change employee's position",
    currentPosition: "Current Position",
    newPosition: "New Position",
    noPosition: "No Position",
    changePositionFor: "Change Position: {{name}}",
    viewProfile: "View Full Profile",
    documentsCount: "documents",
    uploadDocument: "Upload Document",
    selectFiles: "Select Files",
    uploadAll: "Upload All",
    uploading: "Uploading...",
    pending: "Pending",
    noDocuments: "No documents uploaded yet",
    documentsInfo:
      "💡 You can upload and view documents like contracts, certificates, ID",
    fileTooLarge: "File is larger than allowed limit (10 MB)",
    filesSelected: "Files selected. Click 'Upload All' to upload",
    fileUploaded: "File uploaded successfully",
    filesUploaded: "Files uploaded successfully",
    uploadFailed: "Failed to upload files",
    fileDeleted: "Document deleted successfully",
    deleteFailed: "Failed to delete document",
  },

  // ========================================================================
  // DASHBOARD & STATISTICS
  // ========================================================================
  dashboard: {
    title: "Employees Dashboard",
    subtitle: "Comprehensive overview of employee statistics and metrics",
    loadingStats: "Loading statistics...",
    errorLoading: "Error loading data",
    retry: "Retry",
    noData: "No data available",
    lastUpdated: "Last Updated",

    // KPIs
    kpis: {
      totalEmployees: {
        title: "Total Employees",
        description: "Total number of employees in the system",
      },
      activeEmployees: {
        title: "Active Employees",
        description: "Number of currently active employees",
      },
      inactiveEmployees: {
        title: "Inactive Employees",
        description: "Number of inactive employees",
      },
      onLeaveEmployees: {
        title: "On Leave",
        description: "Number of employees currently on leave",
      },
      newHires: {
        title: "New Hires",
        description: "Number of new employees in the last 30 days",
      },
      terminations: {
        title: "Terminations",
        description: "Number of terminated employees in the last 30 days",
      },
      turnoverRate: {
        title: "Turnover Rate",
        description: "Employee turnover rate in the last 30 days",
      },
      averageTenure: {
        title: "Average Tenure",
        description: "Average years of service for active employees",
        years: "years",
      },
      probationEmployees: {
        title: "In Probation",
        description:
          "Number of employees in probation period (less than 90 days)",
      },
      maleCount: {
        title: "Male Employees",
        description: "Total number of male employees",
      },
      femaleCount: {
        title: "Female Employees",
        description: "Total number of female employees",
      },
      genderDiversityRatio: {
        title: "Gender Diversity Ratio",
        description: "Ratio of female to male employees in workforce",
      },
    },

    // Charts
    charts: {
      // Employment Type Distribution
      employmentTypeDistribution: {
        title: "Distribution by Employment Type",
        description: "Percentage of each employment type",
        tooltip: "Employee count and percentage for each employment type",
        noData: "No data available",
        legends: {
          employeeCount: "Employee Count",
          percentage: "Percentage",
        },
      },

      // Status Breakdown
      statusBreakdown: {
        title: "Distribution by Status",
        description: "Employee status breakdown",
        tooltip: "Number of employees in each status",
        noData: "No data available",
        legends: {
          active: "Active",
          inactive: "Inactive",
          onLeave: "On Leave",
          suspended: "Suspended",
          terminated: "Terminated",
        },
      },

      // Department Distribution
      departmentDistribution: {
        title: "Distribution by Department",
        description: "Top 8 departments by employee count",
        tooltip: "Number of employees in each department",
        noData: "No departments",
        legends: {
          total: "Total Employees",
          active: "Active",
        },
        showTop: "Show Top",
        departments: "departments",
      },

      // Gender Distribution
      genderDistribution: {
        title: "Distribution by Gender",
        description: "Male to female ratio in workforce",
        tooltip: "Gender diversity in the company",
        noData: "No data available",
        legends: {
          male: "Male",
          female: "Female",
          other: "Other",
        },
      },

      // Age Group Distribution
      ageGroupDistribution: {
        title: "Distribution by Age Group",
        description: "Employee distribution by age ranges",
        tooltip: "Number of employees in each age group",
        noData: "No data available",
        legends: {
          ageGroup: "Age Group",
          count: "Count",
          averageAge: "Average Age",
        },
      },

      // Nationality Distribution
      nationalityDistribution: {
        title: "Distribution by Nationality",
        description: "Top 10 nationalities in the company",
        tooltip: "Diversity in nationalities",
        noData: "No data available",
        showTop: "Show Top",
        nationalities: "nationalities",
      },

      // Position Breakdown
      positionBreakdown: {
        title: "Distribution by Position",
        description: "Top 10 positions in the company",
        tooltip: "Number of employees in each position",
        noData: "No data available",
        showTop: "Show Top",
        positions: "positions",
        legends: {
          count: "Count",
          percentage: "Percentage",
        },
      },

      // Monthly Hiring Trend
      monthlyHiringTrend: {
        title: "Monthly Hiring Trend",
        description: "New hires and terminations over the last 12 months",
        tooltip: "Number of new hires, terminations, and total employees",
        noData: "No data available",
        legends: {
          newHires: "New Hires",
          terminations: "Terminations",
          netChange: "Net Change",
          totalEmployees: "Total Employees",
        },
      },
    },

    // Export Options
    export: {
      title: "Export Data",
      pdf: "Export PDF",
      excel: "Export Excel",
      print: "Print",
    },

    // Filters
    filters: {
      title: "Filters",
      dateRange: "Date Range",
      startDate: "Start Date",
      endDate: "End Date",
      department: "Department",
      employmentType: "Employment Type",
      applyFilters: "Apply Filters",
      clearFilters: "Clear Filters",
      allDepartments: "All Departments",
      allTypes: "All Types",
    },
  },
};
