import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../../../../infrastructure/database/prisma/prisma.service';
import { Prisma } from '@prisma/client';
import { CostAllocationEntity } from '../entities/cost-allocation.entity';

/**
 * Cost Allocation Repository
 *
 * Handles all database operations for cost allocations
 * Used when costs are distributed across multiple projects
 *
 * Design Pattern: Repository Pattern (Clean Architecture)
 * - Isolates database logic from business logic
 * - Makes testing easier (can mock repository)
 * - Allows changing database without affecting use cases
 *
 * Transaction Management:
 * - All multi-record operations should be wrapped in transactions
 * - Ensures data consistency (all succeed or all fail)
 *
 * @class CostAllocationRepository
 */
@Injectable()
export class CostAllocationRepository {
  private readonly logger = new Logger(CostAllocationRepository.name);

  constructor(private prisma: PrismaService) {}

  /**
   * Create multiple allocations for a cost
   *
   * Used when:
   * - Creating a new allocated cost
   * - Replacing existing allocations
   *
   * Important: This should be called within a transaction
   * The caller is responsible for transaction management
   *
   * @param costId - Parent cost ID
   * @param allocations - Array of allocation data
   * @param tx - Optional transaction client
   * @returns Created allocations
   */
  async createMany(
    costId: string,
    allocations: Array<{
      projectId: string;
      allocatedAmount: number;
      percentage: number;
      notes?: string;
    }>,
    tx?: Prisma.TransactionClient,
  ): Promise<CostAllocationEntity[]> {
    const client = tx || this.prisma;

    this.logger.log(
      `Creating ${allocations.length} allocations for cost ${costId}`,
    );

    // Transform data for Prisma
    // Note: id is auto-generated by database (@default(uuid()) in schema)
    const data = allocations.map((allocation) => ({
      costId,
      projectId: allocation.projectId,
      allocatedAmount: allocation.allocatedAmount,
      percentage: allocation.percentage,
      notes: allocation.notes,
    }));

    // Batch create
    await client.costAllocation.createMany({
      data,
      skipDuplicates: false, // Should throw error if duplicate cost-project pair
    });

    // Fetch created records with relations
    return this.findByCostId(costId, client);
  }

  /**
   * Find all allocations for a specific cost
   *
   * Used when:
   * - Displaying cost details
   * - Validating allocation sum
   * - Updating allocations
   *
   * @param costId - Cost ID
   * @param tx - Optional transaction client
   * @param includeProject - Include project details (default: true)
   * @returns Array of allocations
   */
  async findByCostId(
    costId: string,
    tx?: Prisma.TransactionClient,
    includeProject = true,
  ): Promise<CostAllocationEntity[]> {
    const client = tx || this.prisma;

    const allocations = await client.costAllocation.findMany({
      where: { costId },
      include: includeProject
        ? {
            project: {
              select: {
                id: true,
                projectCode: true,
                name: true,
                status: true,
              },
            },
          }
        : undefined,
      orderBy: { createdAt: 'desc' },
    });

    // Convert Decimal to number for entity
    return allocations.map((a) => ({
      ...a,
      allocatedAmount: Number(a.allocatedAmount),
      percentage: Number(a.percentage),
    })) as unknown as CostAllocationEntity[];
  }

  /**
   * Find all allocations for a specific project
   *
   * Used when:
   * - Viewing project financials
   * - Calculating total allocated costs to project
   * - Project reports
   *
   * @param projectId - Project ID
   * @param tx - Optional transaction client
   * @returns Array of allocations
   */
  async findByProjectId(
    projectId: string,
    tx?: Prisma.TransactionClient,
  ): Promise<CostAllocationEntity[]> {
    const client = tx || this.prisma;

    const allocations = await client.costAllocation.findMany({
      where: { projectId },
      include: {
        cost: true, // Include parent cost details
      },
      orderBy: { createdAt: 'desc' },
    });

    // Convert Decimal to number for entity
    return allocations.map((a) => ({
      ...a,
      allocatedAmount: Number(a.allocatedAmount),
      percentage: Number(a.percentage),
    })) as unknown as CostAllocationEntity[];
  }

  /**
   * Update allocations for a cost
   *
   * Strategy: Full replacement
   * - Delete all existing allocations
   * - Create new allocations
   *
   * Why full replacement?
   * 1. Simpler logic - no diff calculation
   * 2. Ensures sum always equals 100%
   * 3. Better audit trail (clear before/after states)
   * 4. Prevents orphaned allocations
   *
   * Important: Must be called within a transaction
   *
   * @param costId - Cost ID
   * @param allocations - New allocation data
   * @param tx - Transaction client (required)
   * @returns Updated allocations
   */
  async updateAllocations(
    costId: string,
    allocations: Array<{
      projectId: string;
      allocatedAmount: number;
      percentage: number;
      notes?: string;
    }>,
    tx: Prisma.TransactionClient,
  ): Promise<CostAllocationEntity[]> {
    this.logger.log(`Updating allocations for cost ${costId}`);

    // Step 1: Delete existing allocations
    await this.deleteByCostId(costId, tx);

    // Step 2: Create new allocations
    return this.createMany(costId, allocations, tx);
  }

  /**
   * Delete all allocations for a cost
   *
   * Used when:
   * - Converting allocated cost to single project cost
   * - Converting allocated cost to general expense
   * - Updating allocations (as part of replacement)
   * - Deleting a cost (cascade delete)
   *
   * @param costId - Cost ID
   * @param tx - Optional transaction client
   * @returns Number of deleted records
   */
  async deleteByCostId(
    costId: string,
    tx?: Prisma.TransactionClient,
  ): Promise<number> {
    const client = tx || this.prisma;

    const result = await client.costAllocation.deleteMany({
      where: { costId },
    });

    this.logger.log(`Deleted ${result.count} allocations for cost ${costId}`);

    return result.count;
  }

  /**
   * Check if a cost has allocations
   *
   * Performance: Uses exists pattern (faster than count)
   *
   * @param costId - Cost ID
   * @param tx - Optional transaction client
   * @returns true if cost has any allocations
   */
  async hasAllocations(
    costId: string,
    tx?: Prisma.TransactionClient,
  ): Promise<boolean> {
    const client = tx || this.prisma;

    const allocation = await client.costAllocation.findFirst({
      where: { costId },
      select: { id: true },
    });

    return allocation !== null;
  }

  /**
   * Get allocation statistics for a cost
   *
   * Used for:
   * - Validation
   * - Display summaries
   * - Reports
   *
   * @param costId - Cost ID
   * @param tx - Optional transaction client
   * @returns Statistics object
   */
  async getStatistics(
    costId: string,
    tx?: Prisma.TransactionClient,
  ): Promise<{
    count: number;
    totalAmount: number;
    totalPercentage: number;
  }> {
    const client = tx || this.prisma;

    const allocations = await client.costAllocation.findMany({
      where: { costId },
      select: {
        allocatedAmount: true,
        percentage: true,
      },
    });

    return {
      count: allocations.length,
      totalAmount: allocations.reduce(
        (sum, a) => sum + Number(a.allocatedAmount),
        0,
      ),
      totalPercentage: allocations.reduce(
        (sum, a) => sum + Number(a.percentage),
        0,
      ),
    };
  }
}
