import { Injectable, Inject } from '@nestjs/common';
import type { ISiteRepository } from '../repositories';
import { SITE_REPOSITORY } from '../repositories';
import { CreateSiteDto, SiteResponseDto } from '../dto';
import { GenerateSiteCodeUseCase } from './generate-site-code.use-case';

@Injectable()
export class CreateSiteUseCase {
  constructor(
    @Inject(SITE_REPOSITORY)
    private siteRepository: ISiteRepository,
    private generateSiteCode: GenerateSiteCodeUseCase,
  ) {}

  async execute(
    data: CreateSiteDto,
    createdBy: string,
  ): Promise<SiteResponseDto> {
    // Source of truth: site code is always generated by backend.
    // Any incoming `code` from clients is intentionally ignored.
    const siteCode = await this.generateSiteCode.execute();

    // Create site
    const site = await this.siteRepository.create(data, siteCode, createdBy);

    return site.toResponse();
  }
}
