/**
 * Create Employee Deduction Use Case
 * Business logic for creating a new employee deduction
 */

import {
  Injectable,
  Inject,
  NotFoundException,
  BadRequestException,
} from '@nestjs/common';
import { I18nService } from 'nestjs-i18n';
import { WinstonLoggerService } from '../../../../infrastructure/logger/winston-logger.service';
import { PrismaService } from '../../../../infrastructure/database/prisma/prisma.service';
import {
  type IEmployeeDeductionRepository,
  EMPLOYEE_DEDUCTION_REPOSITORY,
} from '../repositories';
import { CreateEmployeeDeductionDto } from '../dto';
import { EmployeeDeductionEntity } from '../entities';
import { DeductionType } from '@prisma/client';
import { assertEmployeeCanReceivePayroll } from './employee-payroll-status.guard';

@Injectable()
export class CreateEmployeeDeductionUseCase {
  constructor(
    @Inject(EMPLOYEE_DEDUCTION_REPOSITORY)
    private readonly employeeDeductionRepository: IEmployeeDeductionRepository,
    private readonly logger: WinstonLoggerService,
    private readonly i18n: I18nService,
    private readonly prisma: PrismaService,
  ) {
    this.logger.setContext(CreateEmployeeDeductionUseCase.name);
  }

  async execute(
    dto: CreateEmployeeDeductionDto,
    userId: string,
  ): Promise<EmployeeDeductionEntity> {
    this.logger.log(
      `Creating employee deduction for employee: ${dto.employeeId}`,
    );

    try {
      // Validate employee exists and is eligible for payroll transactions
      const employee = await this.prisma.employee.findUnique({
        where: { id: dto.employeeId },
        select: { id: true, employeeNumber: true, status: true },
      });
      if (!employee) {
        throw new NotFoundException(`Employee ${dto.employeeId} not found`);
      }
      assertEmployeeCanReceivePayroll(employee);

      // Validate amount is positive
      if (dto.amount <= 0) {
        throw new BadRequestException(
          this.i18n.t('payroll.deduction.amountInvalid'),
        );
      }

      // If deduction type is LOAN_REPAYMENT, validate loan exists and is active
      if (dto.deductionType === DeductionType.LOAN_REPAYMENT) {
        // Strict rule:
        // Loan repayments must only be generated by the loan installment flow
        // (PayLoanInstallmentUseCase / payroll processing), never by manual
        // deduction creation. This prevents loan counters and deduction history
        // from drifting out of sync.
        throw new BadRequestException(
          'LOAN_REPAYMENT deductions are system-generated only. Use /payroll/loans/:id/pay.',
        );
      }

      // Create employee deduction
      const employeeDeduction = await this.employeeDeductionRepository.create(
        dto,
        userId,
      );

      this.logger.log(
        `Employee deduction created successfully with ID: ${employeeDeduction.id}`,
      );

      return employeeDeduction;
    } catch (error) {
      this.logger.log(`Failed to create employee deduction: ${error.message}`);
      throw error;
    }
  }
}
