/**
 * Cost Allocation Entity
 *
 * Represents a portion of a cost allocated to a specific project
 * Used when a single cost (equipment, materials, etc.) is shared across multiple projects
 *
 * Business Rules:
 * 1. A cost can have 0 or many allocations (0 = single project or general expense)
 * 2. Must have at least 2 allocations if any exist (minimum distribution)
 * 3. Sum of all allocations must equal parent cost amount
 * 4. Sum of all percentages must equal 100%
 * 5. Each cost-project pair must be unique (enforced by DB constraint)
 *
 * Example Scenario:
 * - Cost: Cement truck = 10,000 SAR
 * - Allocation 1: Villa Project = 4,000 SAR (40%)
 * - Allocation 2: Building Project = 3,500 SAR (35%)
 * - Allocation 3: Shop Project = 2,500 SAR (25%)
 *
 * @class CostAllocationEntity
 */
export class CostAllocationEntity {
  /**
   * Unique identifier (UUID)
   */
  id: string;

  /**
   * Parent cost ID
   * Foreign key to Cost table
   */
  costId: string;

  /**
   * Project ID this allocation belongs to
   * Foreign key to Project table
   */
  projectId: string;

  /**
   * Amount allocated to this project (in SAR)
   * Must be > 0 and <= parent cost amount
   * Stored as Decimal(12,2) in database for precision
   */
  allocatedAmount: number;

  /**
   * Percentage of total cost allocated to this project
   * Range: 0.01 to 100.00
   * Stored as Decimal(5,2) in database
   *
   * Note: Both amount and percentage are stored for flexibility
   * Percentage is calculated if user provides amount, and vice versa
   */
  percentage: number;

  /**
   * Optional notes explaining this allocation
   * Example: "Initial construction phase", "Equipment shared use"
   */
  notes?: string;

  /**
   * Creation timestamp
   * Auto-generated by database
   */
  createdAt: Date;

  /**
   * Last update timestamp
   * Auto-updated by database on any change
   */
  updatedAt: Date;

  // ============================================================================
  // Relations (populated when using include)
  // ============================================================================

  /**
   * Parent cost
   * Use: Include to get full cost details
   */
  cost?: any; // Will be typed as Cost once we rename ProjectCost

  /**
   * Allocated to project
   * Use: Include to get project name, code, status
   */
  project?: {
    id: string;
    projectCode: string;
    name: string;
    status: string;
  };
}
